import{buildYbus,branchFlows,solvePowerFlow}from'./powerflow.js';
import{solveComplex,cadd,csub,cmul,cdiv,cconj,cabs,zeros}from'../math/linalg.js';
import{initClassical,initGENROU,initGENSAL,machineNorton,machineElectrical,machineDerivatives}from'../models/machines.js';
import{initTGOV1,derivTGOV1,initEXST1,derivEXST1,initPSS1A,derivPSS1A}from'../models/controllers.js';
import{compositeLoadPower,initMotor,motorDerivative}from'../models/loads.js';
import{ProtectionEngine}from'../models/protection.js';
import{CoordinatedMPC}from'./mpc.js';
const DEG=180/Math.PI;
const LIB={gov:{R:.05,VMAX:1.2,VMIN:0,T1:.1,T2:.2,T3:10,Dt:0},exc:{TR:.01,VIMAX:.2,VIMIN:-.2,TC:1,TB:1,KA:80,TA:.05,VRMAX:8,VRMIN:-3,KC:.2,KF:.1,TF:1},pss:{K:10,Tw:10,T1:.1,T2:.02,T3:.1,T4:.02,Vmax:.1,Vmin:-.1}};
function cloneState(s){return structuredClone(s)}
function addScaled(s,d,h){const n=cloneState(s);n.agc+=h*d.agc;for(let i=0;i<n.machines.length;i++){for(const[k,v]of Object.entries(d.machines[i].machine))n.machines[i].machine[k]=(n.machines[i].machine[k]??0)+h*v;for(const group of['gov','exc','pss'])for(const[k,v]of Object.entries(d.machines[i][group]||{}))n.machines[i][group][k]=(n.machines[i][group][k]??0)+h*v}for(let i=0;i<n.loads.length;i++)if(d.loads[i])for(const[k,v]of Object.entries(d.loads[i]))n.loads[i][k]=(n.loads[i][k]??0)+h*v;return n}
function combineRK4(s,k1,k2,k3,k4,h){const n=cloneState(s),comb=(base,a,b,c,d)=>base+h*(a+2*b+2*c+d)/6;n.agc=comb(s.agc,k1.agc,k2.agc,k3.agc,k4.agc);for(let i=0;i<n.machines.length;i++){for(const group of['machine','gov','exc','pss']){const keys=new Set([...Object.keys(k1.machines[i][group]||{}),...Object.keys(k2.machines[i][group]||{}),...Object.keys(k3.machines[i][group]||{}),...Object.keys(k4.machines[i][group]||{})]);for(const key of keys)n.machines[i][group][key]=comb(s.machines[i][group][key]??0,k1.machines[i][group]?.[key]??0,k2.machines[i][group]?.[key]??0,k3.machines[i][group]?.[key]??0,k4.machines[i][group]?.[key]??0)}}for(let i=0;i<n.loads.length;i++){const keys=new Set([...Object.keys(k1.loads[i]||{}),...Object.keys(k2.loads[i]||{})]);for(const key of keys)n.loads[i][key]=comb(s.loads[i][key]??0,k1.loads[i]?.[key]??0,k2.loads[i]?.[key]??0,k3.loads[i]?.[key]??0,k4.loads[i]?.[key]??0)}return n}
function voltageComplex(pf){return pf.Vm.map((m,i)=>[m*Math.cos(pf.Va[i]/DEG),m*Math.sin(pf.Va[i]/DEG)])}
function resolveBusNumber(mpc,bus){const mapped=mpc.gridmpc?.busMap?.[String(bus)];if(mapped!=null)return Number(mapped);const n=Number(bus);if(!Number.isFinite(n))throw new Error('Unknown bus reference '+bus);return n}
function busIndex(mpc,bus){return resolveBusNumber(mpc,bus)-1}
function genForBus(mpc,bus){const no=resolveBusNumber(mpc,bus);return mpc.gen.find(g=>g[0]===no)}
function initState(project,mpc,pf){const V=voltageComplex(pf),machines=project.devices.generators.filter(g=>g.enabled!==false).map(g=>{const gg=genForBus(mpc,g.bus),busNo=resolveBusNumber(mpc,g.bus),S=[(g.P0??gg?.[1]??0)/mpc.baseMVA,-(g.Q0??gg?.[2]??0)/mpc.baseMVA],p={...g.params,H:g.H??g.params.H,D:g.D??0},machine=g.model==='GENROU'?initGENROU({V:V[busNo-1],S,p}):g.model==='GENSAL'?initGENSAL({V:V[busNo-1],S,p}):initClassical({V:V[busNo-1],S,p});return{id:g.id,bus:busNo,sourceBus:g.bus,model:g.model,p,active:true,machine,gov:initTGOV1(LIB.gov,machine.Pm/(g.Sn/100||1)),exc:initEXST1(pf.Vm[g.bus-1],machine.Efd||1,LIB.exc),pss:initPSS1A(),vref:pf.Vm[g.bus-1],Sn:g.Sn||100}});
 const loads=project.devices.loads.map(l=>l.motorFraction?initMotor(l):{});return{machines,loads,agc:0,loadScale:Array(project.devices.loads.length).fill(1),openedBranches:new Set()}}
function makeNetworkMatrix(mpc,state,faultBus=0){const{G,B}=buildYbus(mpc),n=mpc.bus.length,A=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>[G[i][j],B[i][j]]));for(let k=0;k<state.machines.length;k++){const m=state.machines[k];if(!m.active)continue;const no=machineNorton(m.model,m.machine,m.p),i=m.bus-1;A[i][i]=cadd(A[i][i],no.Y)}if(faultBus){const i=faultBus-1;A[i][i]=cadd(A[i][i],[1e4,0])}return A}
function currentFromPower(P,Q,V){if(cabs(V)<.05)return[0,0];return cconj(cdiv([P,Q],V))}
function solveAlgebraic(project,mpc,state,{faultBus=0,frequency=60,extraInjections=[]}={}){const n=mpc.bus.length,A=makeNetworkMatrix(mpc,state,faultBus),b=Array.from({length:n},()=>[0,0]);for(const m of state.machines){if(!m.active)continue;const no=machineNorton(m.model,m.machine,m.p);b[m.bus-1]=cadd(b[m.bus-1],no.I)}let V=solveComplex(A,b);
 for(let it=0;it<8;it++){const rhs=b.map(z=>[...z]);for(let q=0;q<project.devices.loads.length;q++){const l=project.devices.loads[q],li=busIndex(mpc,l.bus),mag=Math.max(.05,cabs(V[li])),Pq=compositeLoadPower({...l,P0:l.P0*state.loadScale[q],Q0:l.Q0*state.loadScale[q]},state.loads[q],mag,frequency,project.network.frequencyHz),I=currentFromPower(Pq.P,Pq.Q,V[li]);rhs[li]=csub(rhs[li],I)}for(const inj of extraInjections){if(!inj.enabled||Math.abs(inj.Ppu)+Math.abs(inj.Qpu)<1e-12)continue;rhs[inj.bus-1]=cadd(rhs[inj.bus-1],currentFromPower(inj.Ppu,inj.Qpu,V[inj.bus-1]))}const nv=solveComplex(A,rhs);let e=0;for(let i=0;i<n;i++)e=Math.max(e,cabs(csub(nv[i],V[i])));V=nv;if(e<1e-9)break}
 return V}
function coi(state,project){let num=0,den=0;for(const m of state.machines){if(!m.active)continue;const H=m.p.H,base=m.Sn/100;num+=H*base*m.machine.omega;den+=H*base}return den?num/den:1}
function distributeFleet(project,mpc,totalMW,time){const active=(project.devices.fleet||[]).filter(u=>u.enabled!==false&&(u.connect==null||time>=u.connect)&&(u.disconnect==null||time<u.disconnect)),cap=active.reduce((s,u)=>s+(u.pmax||0),0);if(!active.length||cap<=0||Math.abs(totalMW)<1e-12)return[];const req=Math.max(-cap,Math.min(cap,totalMW)),sumW=active.reduce((s,u)=>s+(u.participation??u.pmax??1),0)||1;return active.map(u=>({enabled:true,bus:resolveBusNumber(mpc,u.bus),Ppu:req*((u.participation??u.pmax??1)/sumW)/project.network.baseMVA,Qpu:0,id:u.id}))}
function securityProjectCommand(project,mpc,state,t,scenario,frequency,genMW,fleetMW){const faultBus=scenario.type==='fault'&&t>=scenario.start&&t<scenario.clear?scenario.bus:0,check=scale=>{const inj=distributeFleet(project,mpc,fleetMW*scale,t),V=solveAlgebraic(project,mpc,state,{faultBus,frequency,extraInjections:inj}),Vm=V.map(cabs),Va=V.map(v=>Math.atan2(v[1],v[0])*DEG),flows=branchFlows(mpc,Vm,Va),vmin=Math.min(...Vm),line=Math.max(0,...flows.map(x=>x.loadingPct)),limits=project.controls.mpc.security||{vmin:.9,lineMax:130};return{ok:vmin>=(limits.vmin??.9)&&line<=(limits.lineMax??130),V,vmin,line}};let r=check(1);if(r.ok)return{genMW,fleetMW};let lo=0,hi=1,best=0;for(let i=0;i<18;i++){const mid=(lo+hi)/2,q=check(mid);if(q.ok){best=mid;lo=mid}else hi=mid}return{genMW,fleetMW:fleetMW*best}}
function scenarioDisturbanceMW(project,mpc,scenario,t){if(t<scenario.start)return 0;if(scenario.type==='trip'){const g=mpc.gen.find(x=>x[0]===scenario.bus);return g?.[1]??0}if(scenario.type==='loadStep')return (scenario.fraction||0)*mpc.bus.reduce((s,b)=>s+b[2],0);return 0}
function derivative(project,mpc,state,t,scenario,command){const f0=project.network.frequencyHz,coiW=coi(state,project),frequency=f0*coiW,faultBus=scenario.type==='fault'&&t>=scenario.start&&t<scenario.clear?scenario.bus:0,extra=distributeFleet(project,mpc,command?.fleetMW||0,t),V=solveAlgebraic(project,mpc,state,{faultBus,frequency,extraInjections:extra}),d={machines:[],loads:[],agc:0},agcErr=(1-coiW),nativeAgc=project.controls.agc?.enabled&&project.controls.mpc?.mode!=='coordinated',agcCmd=nativeAgc?Math.max(-1,Math.min(1,(project.controls.agc.Ki||.25)*state.agc)):0;d.agc=nativeAgc?agcErr:0;const active=state.machines.filter(x=>x.active),share=active.length?1/active.length:0,mpcGenPu=(command?.genMW||0)/Math.max(1,active.reduce((sum,m)=>sum+m.Sn,0));
 for(let i=0;i<state.machines.length;i++){const m=state.machines[i];if(!m.active){d.machines.push({machine:{delta:0,omega:0},gov:{valve:0,ll:0},exc:{vmeas:0,ll:0,vr:0,fb:0},pss:{xw:0,x1:0,x2:0}});continue}const vm=cabs(V[m.bus-1]),ps=project.controls.pss!==false?derivPSS1A(m.pss,{omega:m.machine.omega},LIB.pss):{d:{xw:0,x1:0,x2:0},out:0},ex=project.controls.exciters!==false?derivEXST1(m.exc,{v:vm,vref:m.vref,pss:ps.out,ifd:0},LIB.exc):{d:{vmeas:0,ll:0,vr:0,fb:0},out:m.machine.Efd||1},paux=agcCmd*share+mpcGenPu,gov=project.controls.governors!==false?derivTGOV1(m.gov,{omega:m.machine.omega,paux},LIB.gov):{d:{valve:0,ll:0},out:m.machine.Pm/(m.Sn/100)},Pm=gov.out*(m.Sn/100),elec=machineElectrical(m.model,m.machine,V[m.bus-1],m.p),md=machineDerivatives(m.model,m.machine,elec,m.p,{Pm,Efd:ex.out});d.machines.push({machine:md,gov:gov.d,exc:ex.d,pss:ps.d})}
 for(let q=0;q<project.devices.loads.length;q++){const l=project.devices.loads[q];d.loads.push(l.motorFraction?motorDerivative(l,state.loads[q],cabs(V[busIndex(mpc,l.bus)]),frequency,f0):{})}
 return{d,V,frequency,coiW,agcCmd,fleetMW:command?.fleetMW||0,mpcGenMW:command?.genMW||0}}
function applyScenario(state,scenario,tPrev,t){if(scenario.type==='trip'&&tPrev<scenario.start&&t>=scenario.start){const m=state.machines.find(x=>x.bus===scenario.bus||x.id===scenario.generatorId);if(m)m.active=false}if(scenario.type==='loadStep'&&t>=scenario.start&&tPrev<scenario.start){for(let i=0;i<state.loadScale.length;i++)state.loadScale[i]*=1+(scenario.fraction||0)}}
export async function simulateDynamics(project,mpc,{scenario={type:'trip',bus:38,start:1},controller=null,dt=project.simulation.dt,endTime=project.simulation.endTime,onProgress}={}){scenario={...scenario,bus:scenario.bus!=null?resolveBusNumber(mpc,scenario.bus):scenario.bus};const pf=solvePowerFlow(mpc,{tolerance:1e-11,maxIterations:40,flatStart:false});if(!pf.converged)throw new Error('Initial AC power flow failed');let s=initState(project,mpc,pf),t=0,prevF=project.network.frequencyHz,protection=new ProtectionEngine((project.devices.relays||[]).map(r=>({...r,bus:r.bus!=null?resolveBusNumber(mpc,r.bus):r.bus}))),rows=[],events=[],nSteps=Math.ceil(endTime/dt),mpcCtl=controller||(project.controls.mpc?.enabled&&['fleet-mpc','coordinated'].includes(project.controls.mpc.mode)?new CoordinatedMPC(project):null),held={genMW:0,fleetMW:0},nextMpc=0,mpcAudit=[];
 const updateMpc=()=>{if(!mpcCtl||t+1e-12<nextMpc)return;const f=project.network.frequencyHz*coi(s,project),dist=scenarioDisturbanceMW(project,mpc,scenario,t),soc=(project.devices.fleet||[]).length?(project.devices.fleet.reduce((a,u)=>a+(u.soc0??.7),0)/project.devices.fleet.length):.7,raw=mpcCtl.solve({dfHz:f-project.network.frequencyHz,genMW:held.genMW,fleetMW:held.fleetMW,disturbanceMW:dist,soc0:soc,time:t,securityProject:cmd=>securityProjectCommand(project,mpc,s,t,scenario,f,cmd.genMW,cmd.fleetMW)});held={...raw.command};if(project.controls.mpc.mode==='fleet-mpc')held.genMW=0;mpcAudit.push(raw);nextMpc=t+(project.controls.mpc.sampleTime||.1)}
 const sample=(time,state,aux)=>{const Vm=aux.V.map(cabs),Va=aux.V.map(v=>Math.atan2(v[1],v[0])*DEG),flows=branchFlows(mpc,Vm,Va),freq=aux.frequency,rocof=(freq-prevF)/dt;prevF=freq;const deltas=state.machines.filter(m=>m.active).map(m=>m.machine.delta*DEG),row={time,frequency:freq,rocof,minVoltage:Math.min(...Vm),maxVoltage:Math.max(...Vm),rotorSeparation:deltas.length?Math.max(...deltas)-Math.min(...deltas):0,branchLoading:Math.max(0,...flows.map(x=>x.loadingPct)),agc:aux.agcCmd,mpcGeneratorMW:aux.mpcGenMW,fleetMW:aux.fleetMW,voltages:Vm,generatorPower:state.machines.reduce((sum,m)=>sum+(m.machine.Pm||0)*mpc.baseMVA,0)};rows.push(row);return row};
 updateMpc();let aux0=derivative(project,mpc,s,t,scenario,held),last=sample(0,s,aux0);
 for(let step=0;step<nSteps;step++){updateMpc();const h=Math.min(dt,endTime-t),r1=derivative(project,mpc,s,t,scenario,held),k1=r1.d,s2=addScaled(s,k1,h/2),k2=derivative(project,mpc,s2,t+h/2,scenario,held).d,s3=addScaled(s,k2,h/2),k3=derivative(project,mpc,s3,t+h/2,scenario,held).d,s4=addScaled(s,k3,h),k4=derivative(project,mpc,s4,t+h,scenario,held).d;s=combineRK4(s,k1,k2,k3,k4,h);applyScenario(s,scenario,t,t+h);t+=h;const aux=derivative(project,mpc,s,t,scenario,held),row=sample(t,s,aux),acts=protection.step(t,h,{frequency:row.frequency,voltage:row.voltages});for(const a of acts){events.push(a);if(a.action.kind==='trip-generator'){const m=s.machines.find(x=>x.id===a.action.id||x.bus===a.action.bus);if(m)m.active=false}else if(a.action.kind==='shed-load'){for(let q=0;q<project.devices.loads.length;q++)if(!a.action.bus||project.devices.loads[q].bus===a.action.bus)s.loadScale[q]*=1-a.action.fraction}}last=row;if(step%Math.max(1,Math.floor(nSteps/100))===0)onProgress?.(step/nSteps)}
 const metrics=summarizeDynamics(rows,project,events),solver=mpcCtl?.summary?.()||null;return{rows,metrics,events,initialPowerFlow:pf,finalState:s,mpcAudit,solver}}
export function summarizeDynamics(rows,project,events=[]){const f0=project.network.frequencyHz,nadir=Math.min(...rows.map(r=>r.frequency)),peakRoCoF=Math.max(...rows.map(r=>Math.abs(r.rocof))),minV=Math.min(...rows.map(r=>r.minVoltage)),maxBranch=Math.max(...rows.map(r=>r.branchLoading)),maxAngle=Math.max(...rows.map(r=>r.rotorSeparation)),finalFrequency=rows.at(-1)?.frequency??NaN;let restore=null;for(let i=rows.length-1;i>=0;i--){if(Math.abs(rows[i].frequency-f0)>.02){restore=rows[i+1]?.time??null;break}}return{nadir,peakRoCoF,minVoltage:minV,maxBranchLoading:maxBranch,maxRotorSeparation:maxAngle,finalFrequency,restoreTime:restore,events:events.length}}
export async function convergenceStudy(project,mpc,scenario){const dts=[.02,.01,.005],runs=[];for(const dt of dts){const r=await simulateDynamics(project,mpc,{scenario,dt,endTime:Math.min(project.simulation.endTime,10)});runs.push({dt,...r.metrics})}return runs}