import{buildYbus,branchFlows,solvePowerFlow}from'./powerflow.js';
import{solveComplex,cadd,csub,cmul,cdiv,cconj,cabs,zeros}from'../math/linalg.js';
import{initClassical,initGENROU,initGENSAL,machineNorton,machineElectrical,machineDerivatives}from'../models/machines.js';
import{initTGOV1,derivTGOV1,initEXST1,derivEXST1,initPSS1A,derivPSS1A}from'../models/controllers.js';
import{compositeLoadPower,initMotor,motorDerivative}from'../models/loads.js';
import{ProtectionEngine}from'../models/protection.js';
const DEG=180/Math.PI;
const LIB={gov:{R:.05,VMAX:1.2,VMIN:0,T1:.1,T2:.2,T3:10,Dt:0},exc:{TR:.01,VIMAX:.2,VIMIN:-.2,TC:1,TB:1,KA:80,TA:.05,VRMAX:8,VRMIN:-3,KC:.2,KF:.1,TF:1},pss:{K:10,Tw:10,T1:.1,T2:.02,T3:.1,T4:.02,Vmax:.1,Vmin:-.1}};
function cloneState(s){return structuredClone(s)}
function addScaled(s,d,h){const n=cloneState(s);n.agc+=h*d.agc;for(let i=0;i<n.machines.length;i++){for(const[k,v]of Object.entries(d.machines[i].machine))n.machines[i].machine[k]=(n.machines[i].machine[k]??0)+h*v;for(const group of['gov','exc','pss'])for(const[k,v]of Object.entries(d.machines[i][group]||{}))n.machines[i][group][k]=(n.machines[i][group][k]??0)+h*v}for(let i=0;i<n.loads.length;i++)if(d.loads[i])for(const[k,v]of Object.entries(d.loads[i]))n.loads[i][k]=(n.loads[i][k]??0)+h*v;return n}
function combineRK4(s,k1,k2,k3,k4,h){const n=cloneState(s),comb=(base,a,b,c,d)=>base+h*(a+2*b+2*c+d)/6;n.agc=comb(s.agc,k1.agc,k2.agc,k3.agc,k4.agc);for(let i=0;i<n.machines.length;i++){for(const group of['machine','gov','exc','pss']){const keys=new Set([...Object.keys(k1.machines[i][group]||{}),...Object.keys(k2.machines[i][group]||{}),...Object.keys(k3.machines[i][group]||{}),...Object.keys(k4.machines[i][group]||{})]);for(const key of keys)n.machines[i][group][key]=comb(s.machines[i][group][key]??0,k1.machines[i][group]?.[key]??0,k2.machines[i][group]?.[key]??0,k3.machines[i][group]?.[key]??0,k4.machines[i][group]?.[key]??0)}}for(let i=0;i<n.loads.length;i++){const keys=new Set([...Object.keys(k1.loads[i]||{}),...Object.keys(k2.loads[i]||{})]);for(const key of keys)n.loads[i][key]=comb(s.loads[i][key]??0,k1.loads[i]?.[key]??0,k2.loads[i]?.[key]??0,k3.loads[i]?.[key]??0,k4.loads[i]?.[key]??0)}}return n}
function voltageComplex(pf){return pf.Vm.map((m,i)=>[m*Math.cos(pf.Va[i]/DEG),m*Math.sin(pf.Va[i]/DEG)])}
function genForBus(mpc,bus){return mpc.gen.find(g=>g[0]===bus)}
function initState(project,mpc,pf){const V=voltageComplex(pf),machines=project.devices.generators.filter(g=>g.enabled!==false).map(g=>{const gg=genForBus(mpc,g.bus),S=[(g.P0??gg?.[1]??0)/mpc.baseMVA,-(g.Q0??gg?.[2]??0)/mpc.baseMVA],p={...g.params,H:g.H??g.params.H,D:g.D??0},machine=g.model==='GENROU'?initGENROU({V:V[g.bus-1],S,p}):g.model==='GENSAL'?initGENSAL({V:V[g.bus-1],S,p}):initClassical({V:V[g.bus-1],S,p});return{id:g.id,bus:g.bus,model:g.model,p,active:true,machine,gov:initTGOV1(LIB.gov,machine.Pm/(g.Sn/100||1)),exc:initEXST1(pf.Vm[g.bus-1],machine.Efd||1,LIB.exc),pss:initPSS1A(),vref:pf.Vm[g.bus-1],Sn:g.Sn||100}});
 const loads=project.devices.loads.map(l=>l.motorFraction?initMotor(l):{});return{machines,loads,agc:0,loadScale:Array(project.devices.loads.length).fill(1),openedBranches:new Set()}}
function makeNetworkMatrix(mpc,state,faultBus=0){const{G,B}=buildYbus(mpc),n=mpc.bus.length,A=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>[G[i][j],B[i][j]]));for(let k=0;k<state.machines.length;k++){const m=state.machines[k];if(!m.active)continue;const no=machineNorton(m.model,m.machine,m.p),i=m.bus-1;A[i][i]=cadd(A[i][i],no.Y)}if(faultBus){const i=faultBus-1;A[i][i]=cadd(A[i][i],[1e4,0])}return A}
function currentFromPower(P,Q,V){if(cabs(V)<.05)return[0,0];return cconj(cdiv([P,Q],V))}
function solveAlgebraic(project,mpc,state,{faultBus=0,frequency=60,extraInjections=[]}={}){const n=mpc.bus.length,A=makeNetworkMatrix(mpc,state,faultBus),b=Array.from({length:n},()=>[0,0]);for(const m of state.machines){if(!m.active)continue;const no=machineNorton(m.model,m.machine,m.p);b[m.bus-1]=cadd(b[m.bus-1],no.I)}let V=solveComplex(A,b);
 for(let it=0;it<8;it++){const rhs=b.map(z=>[...z]);for(let q=0;q<project.devices.loads.length;q++){const l=project.devices.loads[q],mag=Math.max(.05,cabs(V[l.bus-1])),Pq=compositeLoadPower({...l,P0:l.P0*state.loadScale[q],Q0:l.Q0*state.loadScale[q]},state.loads[q],mag,frequency,project.network.frequencyHz),I=currentFromPower(Pq.P,Pq.Q,V[l.bus-1]);rhs[l.bus-1]=csub(rhs[l.bus-1],I)}for(const inj of extraInjections){if(!inj.enabled||Math.abs(inj.Ppu)+Math.abs(inj.Qpu)<1e-12)continue;rhs[inj.bus-1]=cadd(rhs[inj.bus-1],currentFromPower(inj.Ppu,inj.Qpu,V[inj.bus-1]))}const nv=solveComplex(A,rhs);let e=0;for(let i=0;i<n;i++)e=Math.max(e,cabs(csub(nv[i],V[i])));V=nv;if(e<1e-9)break}
 return V}
function coi(state,project){let num=0,den=0;for(const m of state.machines){if(!m.active)continue;const H=m.p.H,base=m.Sn/100;num+=H*base*m.machine.omega;den+=H*base}return den?num/den:1}
function derivative(project,mpc,state,t,scenario,control){const f0=project.network.frequencyHz,coiW=coi(state,project),frequency=f0*coiW,faultBus=scenario.type==='fault'&&t>=scenario.start&&t<scenario.clear?scenario.bus:0,extra=control?.injections?.(t,state)||[],V=solveAlgebraic(project,mpc,state,{faultBus,frequency,extraInjections:extra}),d={machines:[],loads:[],agc:0},agcErr=(1-coiW),agcCmd=project.controls.agc?.enabled?Math.max(-1,Math.min(1,(project.controls.agc.Ki||.25)*state.agc)):0;d.agc=project.controls.agc?.enabled?agcErr:0;
 for(let i=0;i<state.machines.length;i++){const m=state.machines[i];if(!m.active){d.machines.push({machine:{delta:0,omega:0},gov:{valve:0,ll:0},exc:{vmeas:0,ll:0,vr:0,fb:0},pss:{xw:0,x1:0,x2:0}});continue}const vm=cabs(V[m.bus-1]),ps=project.controls.pss!==false?derivPSS1A(m.pss,{omega:m.machine.omega},LIB.pss):{d:{xw:0,x1:0,x2:0},out:0},ex=project.controls.exciters!==false?derivEXST1(m.exc,{v:vm,vref:m.vref,pss:ps.out,ifd:0},LIB.exc):{d:{vmeas:0,ll:0,vr:0,fb:0},out:m.machine.Efd||1},participation=1/state.machines.filter(x=>x.active).length,gov=project.controls.governors!==false?derivTGOV1(m.gov,{omega:m.machine.omega,paux:agcCmd*participation},LIB.gov):{d:{valve:0,ll:0},out:m.machine.Pm/(m.Sn/100)},Pm=gov.out*(m.Sn/100),elec=machineElectrical(m.model,m.machine,V[m.bus-1],m.p),md=machineDerivatives(m.model,m.machine,elec,m.p,{Pm,Efd:ex.out});d.machines.push({machine:md,gov:gov.d,exc:ex.d,pss:ps.d})}
 for(let q=0;q<project.devices.loads.length;q++){const l=project.devices.loads[q];d.loads.push(l.motorFraction?motorDerivative(l,state.loads[q],cabs(V[l.bus-1]),frequency,f0):{})}
 return{d,V,frequency,coiW,agcCmd}}
function applyScenario(state,scenario,tPrev,t){if(scenario.type==='trip'&&tPrev<scenario.start&&t>=scenario.start){const m=state.machines.find(x=>x.bus===scenario.bus||x.id===scenario.generatorId);if(m)m.active=false}if(scenario.type==='loadStep'&&t>=scenario.start&&tPrev<scenario.start){for(let i=0;i<state.loadScale.length;i++)state.loadScale[i]*=1+(scenario.fraction||0)}}
export async function simulateDynamics(project,mpc,{scenario={type:'trip',bus:38,start:1},controller=null,dt=project.simulation.dt,endTime=project.simulation.endTime,onProgress}={}){const pf=solvePowerFlow(mpc,{tolerance:1e-11,maxIterations:40,flatStart:false});if(!pf.converged)throw new Error('Initial AC power flow failed');let s=initState(project,mpc,pf),t=0,prevF=project.network.frequencyHz,protection=new ProtectionEngine(project.devices.relays||[]),rows=[],events=[],nSteps=Math.ceil(endTime/dt);
 const sample=(t,state,aux)=>{const Vm=aux.V.map(cabs),Va=aux.V.map(v=>Math.atan2(v[1],v[0])*DEG),flows=branchFlows(mpc,Vm,Va),freq=aux.frequency,rocof=(freq-prevF)/dt;prevF=freq;const deltas=state.machines.filter(m=>m.active).map(m=>m.machine.delta*DEG),row={time:t,frequency:freq,rocof,minVoltage:Math.min(...Vm),maxVoltage:Math.max(...Vm),rotorSeparation:deltas.length?Math.max(...deltas)-Math.min(...deltas):0,branchLoading:Math.max(0,...flows.map(x=>x.loadingPct)),agc:aux.agcCmd,voltages:Vm,generatorPower:state.machines.reduce((sum,m)=>sum+(m.machine.Pm||0)*mpc.baseMVA,0)};rows.push(row);return row};
 let aux0=derivative(project,mpc,s,t,scenario,controller),last=sample(0,s,aux0);
 for(let step=0;step<nSteps;step++){const h=Math.min(dt,endTime-t),r1=derivative(project,mpc,s,t,scenario,controller),k1=r1.d,s2=addScaled(s,k1,h/2),k2=derivative(project,mpc,s2,t+h/2,scenario,controller).d,s3=addScaled(s,k2,h/2),k3=derivative(project,mpc,s3,t+h/2,scenario,controller).d,s4=addScaled(s,k3,h),k4=derivative(project,mpc,s4,t+h,scenario,controller).d;s=combineRK4(s,k1,k2,k3,k4,h);applyScenario(s,scenario,t,t+h);t+=h;const aux=derivative(project,mpc,s,t,scenario,controller),row=sample(t,s,aux),acts=protection.step(t,h,{frequency:row.frequency,voltage:row.voltages});for(const a of acts){events.push(a);if(a.action.kind==='trip-generator'){const m=s.machines.find(x=>x.id===a.action.id||x.bus===a.action.bus);if(m)m.active=false}else if(a.action.kind==='shed-load'){for(let q=0;q<project.devices.loads.length;q++)if(!a.action.bus||project.devices.loads[q].bus===a.action.bus)s.loadScale[q]*=1-a.action.fraction}}last=row;if(step%Math.max(1,Math.floor(nSteps/100))===0)onProgress?.(step/nSteps)}
 const metrics=summarizeDynamics(rows,project,events);return{rows,metrics,events,initialPowerFlow:pf,finalState:s}}
export function summarizeDynamics(rows,project,events=[]){const f0=project.network.frequencyHz,nadir=Math.min(...rows.map(r=>r.frequency)),peakRoCoF=Math.max(...rows.map(r=>Math.abs(r.rocof))),minV=Math.min(...rows.map(r=>r.minVoltage)),maxBranch=Math.max(...rows.map(r=>r.branchLoading)),maxAngle=Math.max(...rows.map(r=>r.rotorSeparation)),finalFrequency=rows.at(-1)?.frequency??NaN;let restore=null;for(let i=rows.length-1;i>=0;i--){if(Math.abs(rows[i].frequency-f0)>.02){restore=rows[i+1]?.time??null;break}}return{nadir,peakRoCoF,minVoltage:minV,maxBranchLoading:maxBranch,maxRotorSeparation:maxAngle,finalFrequency,restoreTime:restore,events:events.length}}
export async function convergenceStudy(project,mpc,scenario){const dts=[.02,.01,.005],runs=[];for(const dt of dts){const r=await simulateDynamics(project,mpc,{scenario,dt,endTime:Math.min(project.simulation.endTime,10)});runs.push({dt,...r.metrics})}return runs}