import{zeros,eye,matMul,transpose,matVec,dot,norm2,clamp,sub}from'../math/linalg.js';
function madd(A,B){return A.map((r,i)=>r.map((v,j)=>v+B[i][j]))}
function mscale(A,s){return A.map(r=>r.map(v=>v*s))}
function outer(a,b){return a.map(x=>b.map(y=>x*y))}
function addVec(a,b){return a.map((x,i)=>x+b[i])}
function matrixPower(A,n){let R=eye(A.length),B=A;while(n){if(n&1)R=matMul(R,B);B=matMul(B,B);n>>=1}return R}
function discretizeEuler(Ac,Bc,dt){const A=madd(eye(Ac.length),mscale(Ac,dt)),B=mscale(Bc,dt);return{A,B}}
function buildCondensed(A,B,C,D,N,x0,dist,Ed){const nx=A.length,nu=B[0].length,ny=C.length,M=zeros(N*ny,nx),S=zeros(N*ny,N*nu),g=Array(N*ny).fill(0);let Ak=eye(nx);for(let k=0;k<N;k++){Ak=matMul(A,Ak);for(let y=0;y<ny;y++)for(let j=0;j<nx;j++)M[k*ny+y][j]=matMul(C,Ak)[y][j];for(let j=0;j<=k;j++){const Ap=matrixPower(A,k-j),CAB=matMul(C,matMul(Ap,B));for(let y=0;y<ny;y++)for(let u=0;u<nu;u++)S[k*ny+y][j*nu+u]=CAB[y][u]+(j===k?D[y][u]:0)}
 let xd=Array(nx).fill(0);for(let j=0;j<=k;j++){const Ap=matrixPower(A,k-j),inc=matVec(Ap,Ed).map(v=>v*dist);xd=addVec(xd,inc)}const gy=matVec(C,xd);for(let y=0;y<ny;y++)g[k*ny+y]=gy[y]}return{M,S,g}}
function blockDiagWeights(N,weights){const ny=weights.length,Q=zeros(N*ny,N*ny);for(let k=0;k<N;k++)for(let y=0;y<ny;y++)Q[k*ny+y][k*ny+y]=weights[y];return Q}
function deltaMatrix(N,nu){const D=zeros(N*nu,N*nu);for(let k=0;k<N;k++)for(let u=0;u<nu;u++){const i=k*nu+u;D[i][i]=1;if(k>0)D[i][(k-1)*nu+u]=-1}return D}
function quadBuild(S,Q,R,Dd,Rd,baseY,prev){const ST=transpose(S),H=madd(madd(matMul(matMul(ST,Q),S),R),matMul(matMul(transpose(Dd),Rd),Dd)),f=matVec(matMul(ST,Q),baseY);const dprev=Array(prev.length).fill(0);for(let u=0;u<prev.length;u++)dprev[u]=-prev[u];const bias=matVec(matMul(transpose(Dd),Rd),dprev);return{H:mscale(H,2),f:addVec(mscaleVec(f,2),mscaleVec(bias,2))}}
const mscaleVec=(v,s)=>v.map(x=>x*s);
function objective(H,f,x){return .5*dot(x,matVec(H,x))+dot(f,x)}
export class ProjectedQPSolver{
 constructor({tolerance=5e-4,maxIterations=500,adaptive=true,adaptiveMax=1000,stepSize=.25,beta=.5,lineSearch=12}={}){Object.assign(this,{tolerance,maxIterations,adaptive,adaptiveMax,stepSize,beta,lineSearch})}
 solve({H,f,project,warmStart=null}){const n=f.length;let x=warmStart?.length===n?project(warmStart.slice()):project(Array(n).fill(0)),it=0,status='MAX_ITER',kkt=Infinity,residual=Infinity,lastObj=objective(H,f,x),ceiling=this.maxIterations,reason='iteration ceiling reached',start=performance.now();
  const maxCeiling=this.adaptive?Math.max(this.maxIterations,this.adaptiveMax):this.maxIterations;
  for(;;){for(;it<ceiling;it++){const grad=addVec(matVec(H,x),f),pg=sub(x,project(sub(x,grad))),pk=project(sub(x,mscaleVec(grad,this.stepSize)));kkt=norm2(pg);residual=norm2(sub(pk,project(pk)));if(!Number.isFinite(kkt)||!Number.isFinite(lastObj)){status='NUMERICAL_FAIL';reason='non-finite objective/optimality';break}if(kkt<=this.tolerance){status='CONVERGED';reason='projected-KKT tolerance satisfied';break}
    let a=this.stepSize,accepted=false,best=x,bestObj=lastObj;for(let ls=0;ls<this.lineSearch;ls++){const c=project(sub(x,mscaleVec(grad,a))),o=objective(H,f,c);if(Number.isFinite(o)&&o<=lastObj-1e-10){best=c;bestObj=o;accepted=true;break}a*=this.beta}if(!accepted){const c=project(sub(x,mscaleVec(grad,Math.max(a,1e-5)))),o=objective(H,f,c);if(Number.isFinite(o)){best=c;bestObj=o}else{status='NUMERICAL_FAIL';reason='line-search numerical failure';break}}x=best;lastObj=bestObj}
   if(status==='CONVERGED'||status==='NUMERICAL_FAIL')break;if(ceiling>=maxCeiling)break;ceiling=Math.min(maxCeiling,Math.max(ceiling+20,Math.ceil(ceiling*1.7)))}
  if(status==='MAX_ITER'&&kkt<=this.tolerance*2){reason='max iterations; near-converged projected-KKT'}return{x,status,iterations:it,iterationCeiling:ceiling,kkt,residual,objective:lastObj,solveTimeMs:performance.now()-start,reason,acceptable:status==='CONVERGED'||(status==='MAX_ITER'&&kkt<=this.tolerance*2)}}
}
export function aggregateSFR(project,{fleetTau=.12,genTau=.5}={}){const f0=project.network.frequencyHz,base=project.network.baseMVA,H=project.devices.generators.filter(g=>g.enabled!==false).reduce((s,g)=>s+(g.H||g.params?.H||5)*(g.Sn||base)/base,0),D=project.devices.generators.reduce((s,g)=>s+(g.D||0),0)||1,Ac=[[-D/(2*H),f0/(2*H*base),f0/(2*H*base)],[0,-1/genTau,0],[0,0,-1/fleetTau]],Bc=[[0,0],[1/genTau,0],[0,1/fleetTau]],Ed=[-f0/(2*H*base),0,0];return{Ac,Bc,Ed,H,D,base,f0}}
function buildProjection(cfg,N,nu=2){const capF=cfg.fleetCapMW,capG=cfg.genCapMW,rf=cfg.fleetRampMWs*cfg.sampleTime,rg=cfg.genRampMWs*cfg.sampleTime,minF=cfg.fleetMinMW??0,minG=cfg.genMinMW??0,energy=cfg.fleetEnergyMWh??Infinity,soc0=cfg.soc0??.7,socMin=cfg.socMin??.2,eta=cfg.eta??.95,prev=cfg.previousU||[0,0];return U=>{const x=U.slice();let pf=prev[1],pg=prev[0],eAvail=Math.max(0,(soc0-socMin)*energy*3600);for(let k=0;k<N;k++){let g=clamp(x[k*2],minG,capG),f=clamp(x[k*2+1],minF,capF);g=clamp(g,pg-rg,pg+rg);f=clamp(f,pf-rf,pf+rf);const maxEnergy=eAvail/cfg.sampleTime*eta;f=Math.min(f,maxEnergy);eAvail=Math.max(0,eAvail-Math.max(0,f)*cfg.sampleTime/eta);x[k*2]=g;x[k*2+1]=f;pg=g;pf=f}return x}}
export class CoordinatedMPC{
 constructor(project,options={}){this.project=project;this.options={...project.controls.mpc,...options};this.prevSolution=null;this.previousU=[0,0];this.audit=[]}
 reset(){this.prevSolution=null;this.previousU=[0,0];this.audit=[]}
 solve({dfHz,genMW=0,fleetMW=0,disturbanceMW=0,soc0=.7,securityProject=null,time=0}){const o=this.options,N=o.horizon||10,Ts=o.sampleTime||.1,{Ac,Bc,Ed,f0}=aggregateSFR(this.project,o),{A,B}=discretizeEuler(Ac,Bc,Ts),C=[[1,0,0],[Ac[0][0],Ac[0][1],Ac[0][2]]],D=[[0,0],[Bc[0][0],Bc[0][1]]],x0=[dfHz,genMW,fleetMW],cond=buildCondensed(A,B,C,D,N,x0,disturbanceMW,Ed),baseY=addVec(matVec(cond.M,x0),cond.g),Q=blockDiagWeights(N,[o.wFrequency||100,o.wRoCoF||30]),R=mscale(eye(2*N),o.wControl||.002),Dd=deltaMatrix(N,2),Rd=mscale(eye(2*N),o.wDeltaU||.02),prevVec=[...this.previousU],{H,f}=quadBuild(cond.S,Q,R,Dd,Rd,baseY,prevVec),fleet=this.project.devices.fleet.filter(x=>x.enabled!==false),fleetCap=Math.min(o.fleetCapMW??fleet.reduce((s,x)=>s+(x.pmax||0),0),fleet.reduce((s,x)=>s+(x.pmax||0),0)||Infinity),fleetEnergyMWh=fleet.reduce((s,x)=>s+(x.energyMWh||0),0),cfg={sampleTime:Ts,fleetCapMW:fleetCap,genCapMW:o.genCapMW??o.agcReserveMW??800,fleetRampMWs:o.fleetRampMWs??500,genRampMWs:o.genRampMWs??300,fleetEnergyMWh,soc0,socMin:fleet.length?Math.min(...fleet.map(x=>x.socMin??.2)):.2,eta:.95,previousU:this.previousU},baseProj=buildProjection(cfg,N),project=U=>{let x=baseProj(U);if(securityProject){const first=securityProject({genMW:x[0],fleetMW:x[1]});if(first&&Number.isFinite(first.genMW)&&Number.isFinite(first.fleetMW)){x[0]=first.genMW;x[1]=first.fleetMW}}return x},solver=new ProjectedQPSolver({tolerance:o.tolerance,maxIterations:o.maxIterations,adaptive:o.adaptive,adaptiveMax:o.adaptiveMax,stepSize:o.stepSize??.25,beta:o.beta??.5,lineSearch:o.lineSearch??12}),warm=o.warmStart&&this.prevSolution?this.prevSolution:null,res=solver.solve({H,f,project,warmStart:warm});
  this.prevSolution=res.x.slice(2).concat(res.x.slice(-2));this.previousU=[res.x[0],res.x[1]];const predicted=matVec(cond.S,res.x).map((v,i)=>v+baseY[i]),audit={time,...res,command:{genMW:res.x[0],fleetMW:res.x[1]},prediction:Array.from({length:N},(_,k)=>({t:(k+1)*Ts,dfHz:predicted[k*2],rocofHzS:predicted[k*2+1]}))};this.audit.push(audit);return audit}
 summary(){const a=this.audit,n=a.length,counts={CONVERGED:0,MAX_ITER:0,INFEASIBLE:0,NUMERICAL_FAIL:0};for(const x of a)counts[x.status]=(counts[x.status]||0)+1;return{updates:n,counts,convergedPct:n?100*counts.CONVERGED/n:0,acceptedPct:n?100*a.filter(x=>x.acceptable).length/n:0,maxKKT:n?Math.max(...a.map(x=>x.kkt)):0,maxResidual:n?Math.max(...a.map(x=>x.residual)):0,avgIterations:n?a.reduce((s,x)=>s+x.iterations,0)/n:0,maxIterations:n?Math.max(...a.map(x=>x.iterations)):0,totalSolveMs:a.reduce((s,x)=>s+x.solveTimeMs,0)}}
}