import{zeros,solveLinear,maxAbs}from'../math/linalg.js';
const BUS={I:0,TYPE:1,PD:2,QD:3,GS:4,BS:5,VM:7,VA:8,VMAX:11,VMIN:12};
const GEN={BUS:0,PG:1,QG:2,QMAX:3,QMIN:4,VG:5,STATUS:7,PMAX:8,PMIN:9};
const BR={F:0,T:1,R:2,X:3,B:4,RA:5,RB:6,RC:7,TAP:8,SHIFT:9,STATUS:10};
function addY(G,B,i,j,re,im){G[i][j]+=re;B[i][j]+=im}
export function buildYbus(mpc){const n=mpc.bus.length,G=zeros(n,n),B=zeros(n,n);for(const br of mpc.branch){if((br[BR.STATUS]??1)<=0)continue;const i=br[BR.F]-1,j=br[BR.T]-1,r=br[BR.R],x=br[BR.X],bc=br[BR.B]||0,d=r*r+x*x;if(d===0)throw new Error('Zero branch impedance');const g=r/d,b=-x/d,tap=br[BR.TAP]||1,shift=(br[BR.SHIFT]||0)*Math.PI/180,c=Math.cos(shift),s=Math.sin(shift);const tr=tap*c,ti=tap*s,t2=tap*tap;
 addY(G,B,i,i,g/t2,(b+bc/2)/t2);addY(G,B,j,j,g,b+bc/2);
 const den=t2;const yftRe=-(g*tr-b*ti)/den,yftIm=-(b*tr+g*ti)/den;const ytfRe=-(g*tr+b*ti)/den,ytfIm=-(-g*ti+b*tr)/den;
 addY(G,B,i,j,yftRe,yftIm);addY(G,B,j,i,ytfRe,ytfIm)}
 for(const b of mpc.bus){const i=b[BUS.I]-1;addY(G,B,i,i,(b[BUS.GS]||0)/mpc.baseMVA,(b[BUS.BS]||0)/mpc.baseMVA)}
 return{G,B}}
function specs(mpc){const n=mpc.bus.length,P=Array(n).fill(0),Q=Array(n).fill(0);for(const g of mpc.gen){if((g[GEN.STATUS]??1)<=0)continue;P[g[GEN.BUS]-1]+=g[GEN.PG]/mpc.baseMVA;Q[g[GEN.BUS]-1]+=g[GEN.QG]/mpc.baseMVA}for(const b of mpc.bus){const i=b[BUS.I]-1;P[i]-=b[BUS.PD]/mpc.baseMVA;Q[i]-=b[BUS.QD]/mpc.baseMVA}return{P,Q}}
function calcPQ(Vm,Va,G,B){const n=Vm.length,P=Array(n).fill(0),Q=Array(n).fill(0);for(let i=0;i<n;i++)for(let j=0;j<n;j++){const th=Va[i]-Va[j],c=Math.cos(th),s=Math.sin(th);P[i]+=Vm[i]*Vm[j]*(G[i][j]*c+B[i][j]*s);Q[i]+=Vm[i]*Vm[j]*(G[i][j]*s-B[i][j]*c)}return{P,Q}}
export function solvePowerFlow(mpc,{tolerance=1e-10,maxIterations=30,flatStart=true}={}){const n=mpc.bus.length,{G,B}=buildYbus(mpc),{P:Psp,Q:Qsp}=specs(mpc),slack=[],pv=[],pq=[];for(let i=0;i<n;i++){const t=mpc.bus[i][BUS.TYPE];if(t===3)slack.push(i);else if(t===2)pv.push(i);else pq.push(i)}if(slack.length!==1)throw new Error('Power flow requires exactly one reference bus');
 const ns=[...pv,...pq],Vm=mpc.bus.map(b=>flatStart?(b[BUS.TYPE]===2||b[BUS.TYPE]===3?b[BUS.VM]:1):b[BUS.VM]),Va=mpc.bus.map(b=>flatStart?0:b[BUS.VA]*Math.PI/180);let mismatch=Infinity,it=0;
 for(;it<maxIterations;it++){const {P,Q}=calcPQ(Vm,Va,G,B),mis=[...ns.map(i=>Psp[i]-P[i]),...pq.map(i=>Qsp[i]-Q[i])];mismatch=maxAbs(mis);if(mismatch<=tolerance)break;const na=ns.length,nv=pq.length,J=zeros(na+nv,na+nv);
  for(let a=0;a<na;a++){const i=ns[a];for(let b=0;b<na;b++){const j=ns[b];if(i===j)J[a][b]=-Q[i]-B[i][i]*Vm[i]*Vm[i];else{const th=Va[i]-Va[j];J[a][b]=Vm[i]*Vm[j]*(G[i][j]*Math.sin(th)-B[i][j]*Math.cos(th))}}
   for(let b=0;b<nv;b++){const j=pq[b];if(i===j)J[a][na+b]=P[i]/Vm[i]+G[i][i]*Vm[i];else{const th=Va[i]-Va[j];J[a][na+b]=Vm[i]*(G[i][j]*Math.cos(th)+B[i][j]*Math.sin(th))}}}
  for(let a=0;a<nv;a++){const i=pq[a],row=na+a;for(let b=0;b<na;b++){const j=ns[b];if(i===j)J[row][b]=P[i]-G[i][i]*Vm[i]*Vm[i];else{const th=Va[i]-Va[j];J[row][b]=-Vm[i]*Vm[j]*(G[i][j]*Math.cos(th)+B[i][j]*Math.sin(th))}}
   for(let b=0;b<nv;b++){const j=pq[b];if(i===j)J[row][na+b]=Q[i]/Vm[i]-B[i][i]*Vm[i];else{const th=Va[i]-Va[j];J[row][na+b]=Vm[i]*(G[i][j]*Math.sin(th)-B[i][j]*Math.cos(th))}}}
  const dx=solveLinear(J,mis);for(let a=0;a<na;a++)Va[ns[a]]+=dx[a];for(let a=0;a<nv;a++)Vm[pq[a]]+=dx[na+a]}
 const pqcalc=calcPQ(Vm,Va,G,B),VaDeg=Va.map(x=>x*180/Math.PI);return{converged:mismatch<=tolerance,iterations:it,maxMismatch:mismatch,Vm,Va:VaDeg,P:pqcalc.P,Q:pqcalc.Q,Ybus:{G,B},flows:branchFlows(mpc,Vm,VaDeg)}}
export function branchFlows(mpc,Vm,VaDeg){const V=Vm.map((m,i)=>[m*Math.cos(VaDeg[i]*Math.PI/180),m*Math.sin(VaDeg[i]*Math.PI/180)]),out=[];const mul=(a,b)=>[a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]],conj=a=>[a[0],-a[1]],add=(a,b)=>[a[0]+b[0],a[1]+b[1]];for(let k=0;k<mpc.branch.length;k++){const br=mpc.branch[k];if((br[BR.STATUS]??1)<=0)continue;const i=br[BR.F]-1,j=br[BR.T]-1,r=br[BR.R],x=br[BR.X],bc=br[BR.B]||0,d=r*r+x*x,g=r/d,b=-x/d,t=br[BR.TAP]||1,sh=(br[BR.SHIFT]||0)*Math.PI/180,tr=t*Math.cos(sh),ti=t*Math.sin(sh),t2=t*t;const yff=[g/t2,(b+bc/2)/t2],yft=[-(g*tr-b*ti)/t2,-(b*tr+g*ti)/t2],ytf=[-(g*tr+b*ti)/t2,-(-g*ti+b*tr)/t2],ytt=[g,b+bc/2],If=add(mul(yff,V[i]),mul(yft,V[j])),It=add(mul(ytf,V[i]),mul(ytt,V[j])),Sf=mul(V[i],conj(If)),St=mul(V[j],conj(It)),base=mpc.baseMVA,rate=br[BR.RA]||0;out.push({index:k+1,from:i+1,to:j+1,Pf:Sf[0]*base,Qf:Sf[1]*base,Pt:St[0]*base,Qt:St[1]*base,loadingPct:rate>0?Math.max(Math.hypot(...Sf),Math.hypot(...St))*base/rate*100:0})}return out}
export function recoverGenerators(mpc,result){const byBus=new Map();for(let i=0;i<mpc.bus.length;i++){const b=mpc.bus[i],pg=(result.P[i]+b[BUS.PD]/mpc.baseMVA)*mpc.baseMVA,qg=(result.Q[i]+b[BUS.QD]/mpc.baseMVA)*mpc.baseMVA;byBus.set(i+1,{Pg:pg,Qg:qg})}return mpc.gen.map(g=>({...byBus.get(g[GEN.BUS]),bus:g[GEN.BUS]}))}
export function validateSolvedCase(mpc,result){const gen=recoverGenerators(mpc,result);let vm=0,va=0,pg=0,qg=0;for(let i=0;i<mpc.bus.length;i++){vm=Math.max(vm,Math.abs(result.Vm[i]-mpc.bus[i][BUS.VM]));va=Math.max(va,Math.abs(result.Va[i]-mpc.bus[i][BUS.VA]))}for(let k=0;k<Math.min(gen.length,mpc.gen.length);k++){pg=Math.max(pg,Math.abs(gen[k].Pg-mpc.gen[k][GEN.PG]));qg=Math.max(qg,Math.abs(gen[k].Qg-mpc.gen[k][GEN.QG]))}return{vm,va,pg,qg,checked:2*mpc.bus.length+2*mpc.gen.length}}
export function powerFlowSummary(mpc,r){const loss=r.flows.reduce((s,x)=>s+x.Pf+x.Pt,0),worst=Math.max(0,...r.flows.map(x=>x.loadingPct));return{converged:r.converged,iterations:r.iterations,maxMismatch:r.maxMismatch,networkPLossMW:loss,worstBranchPct:worst,minVoltage:Math.min(...r.Vm),maxVoltage:Math.max(...r.Vm)}}