import{canonicalHeader,interpolateSeries,SIGNALS}from'./metrics.js';
function delimiter(line){return [[',',(line.match(/,/g)||[]).length],[';',(line.match(/;/g)||[]).length],['\t',(line.match(/\t/g)||[]).length]].sort((a,b)=>b[1]-a[1])[0][0]}
function split(line,d){return line.split(d).map(x=>x.trim().replace(/^"|"$/g,''))}
function buildReference(headers,raw,source){const data={},mapping={};for(const h of headers){const c=canonicalHeader(h);mapping[h]=c;if(c&&!data[c])data[c]=raw[h].map(Number)}return{source,headers,raw,mapping,data}}
export function parseReferenceText(text,{source='CSV'}={}){const lines=text.replace(/\r/g,'').split('\n').filter(x=>x.trim()&&!x.trim().startsWith('#')),d=delimiter(lines[0]),headers=split(lines[0],d),raw=Object.fromEntries(headers.map(h=>[h,[]]));for(let r=1;r<lines.length;r++){const v=split(lines[r],d);for(let i=0;i<headers.length;i++)raw[headers[i]].push(Number(v[i]))}const ref=buildReference(headers,raw,source);if(!ref.data.time?.length)throw new Error('Reference requires a time column or manual mapping to Time');return ref}
export function parseReferenceJSON(text,{source='JSON'}={}){const j=JSON.parse(text);if(Array.isArray(j)){const headers=Object.keys(j[0]||{}),raw=Object.fromEntries(headers.map(h=>[h,j.map(r=>Number(r[h]))]));const ref=buildReference(headers,raw,source);if(!ref.data.time)throw new Error('Reference requires time');return ref}if(j.data?.time){const headers=Object.keys(j.data),raw=Object.fromEntries(headers.map(h=>[h,j.data[h].map(Number)]));return buildReference(headers,raw,j.source||source)}throw new Error('Unsupported reference JSON')}
export async function importReference(file){const text=await file.text();return file.name.toLowerCase().endsWith('.json')?parseReferenceJSON(text,{source:file.name}):parseReferenceText(text,{source:file.name})}
export function applyReferenceMapping(reference,mapping){const data={};for(const [rawName,canonical] of Object.entries(mapping)){if(!canonical||!reference.raw?.[rawName])continue;data[canonical]=reference.raw[rawName].map(Number)}if(!data.time?.length)throw new Error('Map one column to time');return{...reference,mapping:{...mapping},data}}
export function suggestedMapping(reference){return Object.fromEntries(reference.headers.map(h=>[h,reference.mapping?.[h]||canonicalHeader(h)||'']))}
export function alignReference(reference,gridRows,{offset=0,method='linear'}={}){const target=gridRows.map(r=>r.time),src=reference.data.time.map(t=>t+offset),a={time:target};for(const s of SIGNALS)if(reference.data[s])a[s]=interpolateSeries(src,reference.data[s],target,{method});return a}
export function autoAlign(reference,gridRows,{window=2,step=.01,method='linear'}={}){if(!reference.data.frequency)return{offset:0,rmse:NaN,boundary:false};let best={offset:0,rmse:Infinity};for(let off=-window;off<=window+1e-12;off+=step){const a=alignReference(reference,gridRows,{offset:off,method}),e=[];for(let i=0;i<gridRows.length;i++)if(Number.isFinite(a.frequency[i]))e.push(gridRows[i].frequency-a.frequency[i]);if(e.length){const rmse=Math.sqrt(e.reduce((s,x)=>s+x*x,0)/e.length);if(rmse<best.rmse)best={offset:off,rmse}}}best.boundary=Math.abs(Math.abs(best.offset)-window)<step*1.5;return best}