export class NetworkBuilder{
 constructor({canvas,palette,inspector,project,onChange}){Object.assign(this,{canvas,palette,inspector,project,onChange});this.selected=null;this.tool=null;this.lineStart=null;this.bind()}
 setProject(p){this.project=p;this.render()}
 bind(){const tools=[['bus','Bus'],['line','Line'],['transformer','Transformer'],['generator','Generator'],['load','Load'],['fleet','EV / BESS'],['pv','PV'],['wind','Wind']];this.palette.innerHTML=tools.map(([k,n])=>'<button class="btn" draggable="true" data-tool="'+k+'">'+n+'</button>').join('');this.palette.addEventListener('dragstart',e=>{const b=e.target.closest('[data-tool]');if(b)e.dataTransfer.setData('text/plain',b.dataset.tool)});this.palette.addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(!b)return;this.tool=b.dataset.tool;this.lineStart=null});this.canvas.addEventListener('dragover',e=>e.preventDefault());this.canvas.addEventListener('drop',e=>{e.preventDefault();const t=e.dataTransfer.getData('text/plain');if(t)this.add(t,e.offsetX,e.offsetY)});this.canvas.addEventListener('click',e=>{const n=e.target.closest('.node');if(n)this.select(n.dataset.kind,n.dataset.id);else if(this.tool&&!['line','transformer'].includes(this.tool))this.add(this.tool,e.offsetX,e.offsetY)});this.canvas.addEventListener('pointerdown',e=>this.pointerDown(e))}
 add(kind,x,y){if(kind==='line'||kind==='transformer'){this.tool=kind;return}const p=this.project.get(),id=(crypto.randomUUID?.()||Date.now().toString(36)),pos={x:Math.max(10,x-40),y:Math.max(10,y-20)};if(kind==='bus'){p.network.buses.push({id,name:'Bus '+(p.network.buses.length+1),baseKV:345,type:'PQ',Pd:0,Qd:0,Vm:1,Va:0,ui:pos})}else{const bus=this.nearestBus(x,y);if(!bus)return;const item={id,name:kind.toUpperCase()+' '+id.slice(0,4),bus:bus.number||bus.id,enabled:true,ui:pos};if(kind==='generator')p.devices.generators.push({...item,model:'Classical',Sn:100,H:5,D:0,P0:50,Q0:0,params:{H:5,D:0,xdp:.3,ra:0}});else if(kind==='load')p.devices.loads.push({...item,model:'ZIP',P0:.5,Q0:.15,zip:{zP:.2,iP:.3,pP:.5,zQ:.2,iQ:.3,pQ:.5},Kpf:1,Kqf:0,motorFraction:0});else p.devices.fleet.push({...item,type:kind==='pv'?'PV':kind==='wind'?'Wind':'BatteryInverter',model:kind==='pv'||kind==='wind'?'GridFollowing':'GridFollowing',pmax:20,rampMWs:100,energyMWh:kind==='fleet'?50:0,soc0:.7,socMin:.2,socMax:.9,participation:.1})}this.project.set(p);this.onChange?.();this.render()}
 nearestBus(x,y){const bs=this.project.get().network.buses;if(!bs.length)return null;let best=null,d=Infinity;for(const b of bs){const px=b.ui?.x??0,py=b.ui?.y??0,q=(px-x)**2+(py-y)**2;if(q<d){d=q;best=b}}return best}
 pointerDown(e){const n=e.target.closest('.node');if(!n)return;if(this.tool==='line'||this.tool==='transformer'){if(n.dataset.kind!=='bus')return;if(!this.lineStart){this.lineStart=n.dataset.id;n.classList.add('selected')}else{this.connect(this.lineStart,n.dataset.id,this.tool);this.lineStart=null;this.tool=null}return}let sx=e.clientX,sy=e.clientY,el=n,startX=parseFloat(el.style.left)||0,startY=parseFloat(el.style.top)||0;el.setPointerCapture(e.pointerId);const move=ev=>{el.style.left=startX+ev.clientX-sx+'px';el.style.top=startY+ev.clientY-sy+'px'},up=ev=>{el.releasePointerCapture(ev.pointerId);el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',up);this.storePosition(el)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',up)}
 storePosition(el){const obj=this.find(el.dataset.kind,el.dataset.id);if(obj){obj.ui={x:parseFloat(el.style.left),y:parseFloat(el.style.top)};this.project.set(this.project.get());this.renderEdges()}}
 connect(a,b,kind){if(a===b)return;const p=this.project.get(),A=p.network.buses.find(x=>String(x.id)===String(a)),B=p.network.buses.find(x=>String(x.id)===String(b));if(!A||!B)return;const row={id:crypto.randomUUID?.()||Date.now().toString(36),from:A.number||A.id,to:B.number||B.id,r:.001,x:.02,b:.001,rateA:500,status:1};(kind==='transformer'?p.network.transformers:p.network.branches).push(row);this.project.set(p);this.render()}
 find(kind,id){const p=this.project.get();if(kind==='bus')return p.network.buses.find(x=>String(x.id)===String(id));const map={generator:p.devices.generators,load:p.devices.loads,fleet:p.devices.fleet};return map[kind]?.find(x=>String(x.id)===String(id))}
 select(kind,id){this.selected={kind,id};this.canvas.querySelectorAll('.node').forEach(n=>n.classList.toggle('selected',n.dataset.kind===kind&&n.dataset.id===id));const o=this.find(kind,id);if(!o)return;this.inspector.innerHTML='<h3>'+escapeHtml(o.name||kind)+'</h3>'+Object.entries(o).filter(([k,v])=>['string','number','boolean'].includes(typeof v)&&k!=='id').map(([k,v])=>'<label>'+k+'<input data-prop="'+k+'" value="'+String(v).replace(/"/g,'&quot;')+'"></label>').join('')+'<button id="deleteSelected" class="btn">Delete</button>';this.inspector.querySelectorAll('input[data-prop]').forEach(i=>i.addEventListener('change',()=>{const cur=this.find(kind,id),k=i.dataset.prop,old=cur[k];cur[k]=typeof old==='number'?Number(i.value):typeof old==='boolean'?i.value==='true':i.value;this.project.set(this.project.get());this.onChange?.();this.render()}));this.inspector.querySelector('#deleteSelected').onclick=()=>this.remove(kind,id)}
 remove(kind,id){const p=this.project.get();if(kind==='bus')p.network.buses=p.network.buses.filter(x=>String(x.id)!==String(id));else{const key={generator:'generators',load:'loads',fleet:'fleet'}[kind];if(key)p.devices[key]=p.devices[key].filter(x=>String(x.id)!==String(id))}this.project.set(p);this.selected=null;this.render()}
 render(){const p=this.project.get(),nodes=[];for(const b of p.network.buses)nodes.push(this.nodeHtml('bus',b,b.ui||{x:30+(nodes.length%8)*105,y:30+Math.floor(nodes.length/8)*90}));for(const g of p.devices.generators)nodes.push(this.nodeHtml('generator',g,g.ui||this.devicePos(g.bus,15,-35)));for(const l of p.devices.loads)nodes.push(this.nodeHtml('load',l,l.ui||this.devicePos(l.bus,15,45)));for(const u of p.devices.fleet)nodes.push(this.nodeHtml('fleet',u,u.ui||this.devicePos(u.bus,65,45)));this.canvas.innerHTML='<div id="edgeLayer"></div>'+nodes.join('');this.renderEdges()}
 nodeHtml(kind,o,pos){o.ui=o.ui||pos;const sub=kind==='bus'?(o.number?'Bus '+o.number:o.type||'Bus'):(o.model||o.type||kind);return'<div class="node" data-kind="'+kind+'" data-id="'+o.id+'" style="left:'+o.ui.x+'px;top:'+o.ui.y+'px"><b>'+escapeHtml(o.name||kind)+'</b><small>'+escapeHtml(String(sub))+'</small></div>'}
 devicePos(bus,dx,dy){const b=this.project.get().network.buses.find(x=>String(x.number||x.id)===String(bus)),p=b?.ui||{x:40,y:40};return{x:p.x+dx,y:p.y+dy}}
 renderEdges(){const p=this.project.get(),layer=this.canvas.querySelector('#edgeLayer');if(!layer)return;const bus=id=>p.network.buses.find(x=>String(x.number||x.id)===String(id)),html=[];for(const e of [...p.network.branches,...p.network.transformers]){const a=bus(e.from),b=bus(e.to);if(!a||!b)continue;const ax=(a.ui?.x||0)+43,ay=(a.ui?.y||0)+18,bx=(b.ui?.x||0)+43,by=(b.ui?.y||0)+18,len=Math.hypot(bx-ax,by-ay),ang=Math.atan2(by-ay,bx-ax)*180/Math.PI;html.push('<div class="edge" style="left:'+ax+'px;top:'+ay+'px;width:'+len+'px;transform:rotate('+ang+'deg)"></div>')}layer.innerHTML=html.join('')}
}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}