export function derivative(f,x,{h=Math.cbrt(Number.EPSILON)*Math.max(1,Math.abs(x))}={}){return(f(x+h)-f(x-h))/(2*h)}
export function secondDerivative(f,x,{h=Math.pow(Number.EPSILON,0.25)*Math.max(1,Math.abs(x))}={}){return(f(x+h)-2*f(x)+f(x-h))/(h*h)}
function simpson(f,a,b){const c=(a+b)/2;return(b-a)*(f(a)+4*f(c)+f(b))/6}
function adapt(f,a,b,eps,whole,depth){const c=(a+b)/2,L=simpson(f,a,c),R=simpson(f,c,b),d=L+R-whole;if(depth<=0||Math.abs(d)<=15*eps)return L+R+d/15;return adapt(f,a,c,eps/2,L,depth-1)+adapt(f,c,b,eps/2,R,depth-1)}
export function adaptiveSimpson(f,a,b,{tolerance=1e-10,maxDepth=20}={}){if(a===b)return 0;if(b<a)return-adaptiveSimpson(f,b,a,{tolerance,maxDepth});const whole=simpson(f,a,b);return adapt(f,a,b,tolerance,whole,maxDepth)}
export function newtonRoot(f,x0,{df=null,tolerance=1e-12,maxIterations=50,minDerivative=1e-14}={}){let x=x0;for(let i=0;i<maxIterations;i++){const fx=f(x);if(Math.abs(fx)<=tolerance)return{root:x,residual:fx,iterations:i,converged:true};const d=df?df(x):derivative(f,x);if(!Number.isFinite(d)||Math.abs(d)<minDerivative)return{root:x,residual:fx,iterations:i,converged:false,reason:'derivative singular'};const xn=x-fx/d;if(!Number.isFinite(xn))return{root:x,residual:fx,iterations:i,converged:false,reason:'non-finite step'};if(Math.abs(xn-x)<=tolerance*Math.max(1,Math.abs(xn)))return{root:xn,residual:f(xn),iterations:i+1,converged:true};x=xn}return{root:x,residual:f(x),iterations:maxIterations,converged:false,reason:'max iterations'}}
export function bisection(f,a,b,{tolerance=1e-12,maxIterations=100}={}){let fa=f(a),fb=f(b);if(fa===0)return{root:a,residual:0,iterations:0,converged:true};if(fb===0)return{root:b,residual:0,iterations:0,converged:true};if(fa*fb>0)throw new Error('Bisection bracket does not straddle a root');for(let i=0;i<maxIterations;i++){const c=(a+b)/2,fc=f(c);if(Math.abs(fc)<=tolerance||Math.abs(b-a)/2<=tolerance)return{root:c,residual:fc,iterations:i+1,converged:true};if(fa*fc<=0){b=c;fb=fc}else{a=c;fa=fc}}const c=(a+b)/2;return{root:c,residual:f(c),iterations:maxIterations,converged:false}}
function add(x,k,h){return x.map((v,i)=>v+h*k[i])}
function combine(x,h,terms){return x.map((v,i)=>v+h*terms.reduce((s,[a,k])=>s+a*k[i],0))}
export function rk45(f,t0,x0,t1,{dt=(t1-t0)/100,rtol=1e-7,atol=1e-9,dtMin=1e-9,dtMax=Math.abs(t1-t0)/5,onStep}={}){let t=t0,x=x0.slice(),h=Math.sign(t1-t0)*Math.min(Math.abs(dt),Math.abs(t1-t0)),accepted=0,rejected=0;const dir=Math.sign(t1-t0)||1,out=[{t,x:x.slice()}];while(dir*(t1-t)>1e-15){if(dir*(t+h-t1)>0)h=t1-t;const k1=f(t,x),k2=f(t+h/5,combine(x,h,[[1/5,k1]])),k3=f(t+3*h/10,combine(x,h,[[3/40,k1],[9/40,k2]])),k4=f(t+4*h/5,combine(x,h,[[44/45,k1],[-56/15,k2],[32/9,k3]])),k5=f(t+8*h/9,combine(x,h,[[19372/6561,k1],[-25360/2187,k2],[64448/6561,k3],[-212/729,k4]])),k6=f(t+h,combine(x,h,[[9017/3168,k1],[-355/33,k2],[46732/5247,k3],[49/176,k4],[-5103/18656,k5]])),k7=f(t+h,combine(x,h,[[35/384,k1],[500/1113,k3],[125/192,k4],[-2187/6784,k5],[11/84,k6]])),y5=combine(x,h,[[35/384,k1],[500/1113,k3],[125/192,k4],[-2187/6784,k5],[11/84,k6]]),y4=combine(x,h,[[5179/57600,k1],[7571/16695,k3],[393/640,k4],[-92097/339200,k5],[187/2100,k6],[1/40,k7]]);let err=0;for(let i=0;i<x.length;i++){const sc=atol+rtol*Math.max(Math.abs(x[i]),Math.abs(y5[i]));err=Math.max(err,Math.abs(y5[i]-y4[i])/sc)}if(err<=1){t+=h;x=y5;accepted++;out.push({t,x:x.slice()});onStep?.(t,x)}else rejected++;const fac=Math.min(5,Math.max(.2,.9*Math.pow(Math.max(err,1e-12),-.2)));h=dir*Math.min(dtMax,Math.max(dtMin,Math.abs(h)*fac));if(Math.abs(h)<=dtMin&&err>1)throw new Error('RK45 step underflow')}return{trajectory:out,final:x,accepted,rejected}}