function isPow2(n){return n>0&&(n&(n-1))===0}
function reverseBits(x,b){let y=0;for(let i=0;i<b;i++){y=(y<<1)|(x&1);x>>=1}return y}
export function fftReal(samples){const n=samples.length;if(!isPow2(n))return dftReal(samples);const bits=Math.log2(n),re=Array(n),im=Array(n).fill(0);for(let i=0;i<n;i++)re[reverseBits(i,bits)]=samples[i];for(let size=2;size<=n;size*=2){const half=size/2,ang=-2*Math.PI/size;for(let start=0;start<n;start+=size)for(let k=0;k<half;k++){const c=Math.cos(ang*k),s=Math.sin(ang*k),i=start+k,j=i+half,tr=c*re[j]-s*im[j],ti=s*re[j]+c*im[j],ur=re[i],ui=im[i];re[i]=ur+tr;im[i]=ui+ti;re[j]=ur-tr;im[j]=ui-ti}}return re.map((r,i)=>({re:r,im:im[i],mag:Math.hypot(r,im[i]),phase:Math.atan2(im[i],r)}))}
export function dftReal(samples){const n=samples.length,out=[];for(let k=0;k<n;k++){let re=0,im=0;for(let t=0;t<n;t++){const a=-2*Math.PI*k*t/n;re+=samples[t]*Math.cos(a);im+=samples[t]*Math.sin(a)}out.push({re,im,mag:Math.hypot(re,im),phase:Math.atan2(im,re)})}return out}
export function rms(x){return Math.sqrt(x.reduce((s,v)=>s+v*v,0)/Math.max(1,x.length))}
export function mean(x){return x.reduce((s,v)=>s+v,0)/Math.max(1,x.length)}
export function convolution(a,b){const y=Array(a.length+b.length-1).fill(0);for(let i=0;i<a.length;i++)for(let j=0;j<b.length;j++)y[i+j]+=a[i]*b[j];return y}
export function hann(n){return Array.from({length:n},(_,i)=>n===1?1:.5*(1-Math.cos(2*Math.PI*i/(n-1))))}
export function spectrum(samples,fs,{window='hann'}={}){const w=window==='hann'?hann(samples.length):Array(samples.length).fill(1),x=samples.map((v,i)=>v*w[i]),F=fftReal(x),cg=w.reduce((s,v)=>s+v,0)/samples.length;return F.slice(0,Math.floor(samples.length/2)+1).map((z,k)=>({frequency:k*fs/samples.length,magnitude:(k===0||k===samples.length/2?1:2)*z.mag/(samples.length*cg),phase:z.phase}))}
export function thd(samples,fs,fundamental,{maxHarmonic=50}={}){const S=spectrum(samples,fs),bin=fs/samples.length,index=f=>Math.max(0,Math.min(S.length-1,Math.round(f/bin))),v1=S[index(fundamental)].magnitude;let sum=0,harmonics=[];for(let h=2;h<=maxHarmonic&&h*fundamental<=fs/2;h++){const v=S[index(h*fundamental)].magnitude;sum+=v*v;harmonics.push({h,frequency:h*fundamental,magnitude:v,percent:v1?100*v/v1:NaN})}return{fundamentalMagnitude:v1,thd:v1?Math.sqrt(sum)/v1:NaN,thdPercent:v1?100*Math.sqrt(sum)/v1:NaN,harmonics}}