import{Store}from'./core/store.js';
import{newProject,downloadProject,loadProjectFile,APP_VERSION,fingerprintProject}from'./core/project.js';
import{loadIEEE39}from'./data/ieee39.js';
import{ieee39Generators,ieee39Loads,ieee39Fleet}from'./data/ieee39Dynamic.js';
import{scientificBoundaries,modelLibrary}from'./data/modelLibrary.js';
import{parseMatpower}from'./io/matpower.js';
import{projectToMatpower,matpowerToProjectNetwork}from'./io/projectAdapter.js';
import{solvePowerFlow,validateSolvedCase,powerFlowSummary}from'./engines/powerflow.js';
import{contingencyScreen}from'./engines/contingency.js';
import{acStateEstimation}from'./engines/stateEstimation.js';
import{simulateDynamics,convergenceStudy}from'./engines/dynamics.js';
import{benchmarkMPC,horizonBenchmark,warmStartBenchmark}from'./validation/solverBenchmarks.js';
import{designExperiment,buildMonteCarloCases,experimentFingerprint,cloneExperiment,oneAtATimeSensitivity,cartesianSweep}from'./engines/experiments.js';
import{WorkerPool,cpuBackendInfo}from'./compute/pool.js';
import{webGpuInfo}from'./compute/webgpu.js';
import{NetworkBuilder}from'./ui/networkBuilder.js';
import{drawSeries,exportCanvasPng,seriesSvg}from'./ui/charts.js';
import{importReference,alignReference,autoAlign,applyReferenceMapping,suggestedMapping}from'./validation/importers.js';
import{validateRun,validationCsv}from'./validation/report.js';
import{differentialEvolutionCalibration}from'./engines/calibration.js';
import{defaultMicrogrid,optimizeMicrogrid}from'./engines/microgrid.js';
import{reproducibilityRecord,buildHtmlReport,downloadText,ieeeTable}from'./publication/report.js';
import{benchmarkRegistry,applyBenchmark,benchmarkFingerprint,V10_STRESS_BASELINE}from'./benchmarks/registry.js';
import{addRun,cloneRunAsExperiment}from'./core/runs.js';
import{renderEngineeringToolbox}from'./ui/engineeringToolbox.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const project=new Store(newProject('IEEE 39 Research Project'));
let caseData=null,lastRun=null,reference=null,aligned=null,validation=null,builder=null;
const thresholds={frequencyRmse:.02,rocofRmse:.05,voltageRmse:.01,rotorAngleRmse:1,branchLoadingRmse:5,powerRmse:10,minCorrelation:.98,settleBandHz:.02};
const pipelineSteps=['Build model','Validate','Run','Stress','Tune','Monte Carlo','Cross-tool Validation','Figures / Tables','Report'];

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(v,n=4){return Number.isFinite(v)?Number(v).toFixed(n):'—'}
function badge(status){const c=status==='PASS'||status==='CONVERGED'?'good':status==='FAIL'||status==='VIOLATION'?'bad':'warn';return '<span class="'+c+'">'+esc(status)+'</span>'}
function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+name));$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('#advancedToggle').onclick=()=>setView('advanced');

function hydrateNetwork(mpc){const p=project.get();p.network=matpowerToProjectNetwork(mpc);p.devices.generators=ieee39Generators(mpc);p.devices.loads=ieee39Loads(mpc);p.devices.fleet=ieee39Fleet();p.devices.relays=[];p.modified=new Date().toISOString();project.set(p);caseData=mpc;builder?.setProject(project)}
async function load39(fullOrder=false){const mpc=await loadIEEE39();hydrateNetwork(mpc);if(fullOrder){const p=project.get();p.devices.generators=ieee39Generators(mpc,{fullOrder:true});project.set(p);builder.setProject(project)}renderAll();$('#networkStatus').textContent='IEEE 39-bus loaded — '+project.get().devices.generators.length+' generators, '+project.get().devices.loads.length+' loads.'}
function ensureCase(){const p=project.get();if(!p.network.buses?.length)throw new Error('Load, import, or build a network first.');caseData=projectToMatpower(p);return caseData}

function renderPipeline(){ $('#pipeline').innerHTML=pipelineSteps.map((x,i)=>'<div class="pipe-step" data-pipe="'+i+'"><b>'+(i+1)+'. '+x+'</b><span class="state">ready</span></div>').join('')}
function pipelineState(i,state){const el=$('[data-pipe="'+i+'"]');if(!el)return;el.classList.toggle('done',state==='done');el.classList.toggle('running',state==='running');el.querySelector('.state').textContent=state}
function renderScope(){$('#scientificScope').innerHTML=scientificBoundaries.map(x=>'<div class="scope-item"><span>'+esc(x[0])+'</span><span class="'+(x[1]==='implemented'?'implemented':x[1]==='experimental'?'experimental':'not')+'">'+esc(x[1])+' — '+esc(x[2])+'</span></div>').join('')}
function renderHealth(){const p=project.get(),items=[['Buses',p.network.buses.length],['Generators',p.devices.generators.length],['Flexible resources',p.devices.fleet.length],['Saved runs',p.runs.length],['External reference',reference?'loaded':'none'],['App',APP_VERSION]];$('#projectHealth').innerHTML=items.map(x=>'<div class="metric"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')}
function renderRuns(){const p=project.get();$('#recentRuns').classList.toggle('empty',!p.runs.length);$('#recentRuns').innerHTML=p.runs.length?p.runs.slice(0,8).map(r=>'<div class="run-item"><span><b>'+esc(r.name)+'</b><small class="muted"> '+new Date(r.created).toLocaleString()+'</small></span><span>'+fmt(r.metrics?.nadir,3)+' Hz</span></div>').join(''):'No runs yet.'}
function renderModelPalette(){builder=builder||new NetworkBuilder({canvas:$('#networkCanvas'),palette:$('#modelPalette'),inspector:$('#modelInspector'),project,onChange:()=>{renderHealth();renderControls()}});builder.render()}
function renderControls(){
 const p=project.get(),cards=[
  ['Governor / Turbine','governors',p.controls.governors!==false,'TGOV1'],
  ['AVR / Exciter','exciters',p.controls.exciters!==false,'EXST1'],
  ['PSS','pss',p.controls.pss!==false,'PSS1A'],
  ['AGC','agc',p.controls.agc?.enabled!==false,'Integral secondary control'],
  ['Coordinated MPC','mpc',p.controls.mpc?.enabled!==false,p.controls.mpc?.mode||'coordinated']
 ];
 $('#controlCards').innerHTML=cards.map(([name,key,on,model])=>'<article class="card"><h2>'+name+'</h2><label><input type="checkbox" data-control="'+key+'" '+(on?'checked':'')+'> enabled</label><p class="muted">'+esc(model)+'</p></article>').join('')+
 '<article class="card"><h2>Machine assignment</h2><div class="table-wrap"><table class="table"><thead><tr><th>Gen</th><th>Bus</th><th>Model</th></tr></thead><tbody>'+p.devices.generators.map(g=>'<tr><td>'+g.id+'</td><td>'+g.bus+'</td><td><select data-machine="'+g.id+'"><option '+(g.model==='Classical'?'selected':'')+'>Classical</option><option '+(g.model==='GENROU'?'selected':'')+'>GENROU</option><option '+(g.model==='GENSAL'?'selected':'')+'>GENSAL</option></select></td></tr>').join('')+'</tbody></table></div></article>'+
 '<article class="card"><h2>Model inspector</h2><label>Generator<select id="modelGenSelect">'+p.devices.generators.map(g=>'<option value="'+g.id+'">'+g.id+' · Bus '+g.bus+'</option>').join('')+'</select></label><div id="modelParamEditor"></div></article>';
 $$('[data-control]').forEach(i=>i.onchange=()=>{const pp=project.get(),k=i.dataset.control;if(k==='agc'){pp.controls.agc??={};pp.controls.agc.enabled=i.checked}else if(k==='mpc')pp.controls.mpc.enabled=i.checked;else pp.controls[k]=i.checked;project.set(pp)});
 $$('[data-machine]').forEach(sel=>sel.onchange=()=>{const pp=project.get(),g=pp.devices.generators.find(x=>x.id===sel.dataset.machine);g.model=sel.value;const lib=modelLibrary.machines[g.model].params;g.params={...lib,H:g.H||g.params?.H||lib.H,D:g.D||g.params?.D||0,xdp:g.params?.xdp||lib.xdp};project.set(pp);builder.render();renderControls()});
 const renderModelParams=()=>{const id=$('#modelGenSelect')?.value,g=project.get().devices.generators.find(x=>x.id===id),box=$('#modelParamEditor');if(!g||!box)return;g.controller??={governor:'TGOV1',exciter:'EXST1',pss:'PSS1A'};g.controllerParams??={governor:structuredClone(modelLibrary.governors.TGOV1.params),exciter:structuredClone(modelLibrary.exciters.EXST1.params),pss:structuredClone(modelLibrary.pss.PSS1A.params)};const groups=[['Machine','params',g.params,modelLibrary.machines[g.model]],['Governor','controllerParams.governor',g.controllerParams.governor,modelLibrary.governors[g.controller.governor]],['Exciter','controllerParams.exciter',g.controllerParams.exciter,modelLibrary.exciters[g.controller.exciter]],['PSS','controllerParams.pss',g.controllerParams.pss,modelLibrary.pss[g.controller.pss]]];box.innerHTML=groups.filter(x=>x[2]&&x[3]).map(([label,path,obj,meta])=>'<details><summary>'+label+' · <span class="'+(meta.status?.includes('experimental')?'warn':'good')+'">'+esc(meta.status||'library')+'</span></summary><p class="muted">'+esc(meta.source||meta.fidelity||'')+'</p><div class="param-grid">'+Object.entries(obj).filter(([,v])=>typeof v==='number').map(([k,v])=>'<label>'+k+'<input type="number" step="any" data-param-path="'+path+'.'+k+'" value="'+v+'"></label>').join('')+'</div></details>').join('');box.querySelectorAll('[data-param-path]').forEach(inp=>inp.onchange=()=>{const pp=project.get(),gg=pp.devices.generators.find(x=>x.id===id),parts=inp.dataset.paramPath.split('.'),last=parts.pop();let q=gg;for(const k of parts){q[k]??={};q=q[k]}q[last]=Number(inp.value);project.set(pp)})};
 $('#modelGenSelect')?.addEventListener('change',renderModelParams);renderModelParams();
 const m=p.controls.mpc;$('#mpcAudit').innerHTML='<label>Mode<select id="mpcMode"><option value="off">OFF</option><option value="droop">Droop</option><option value="fleet-mpc">Fleet-only MPC</option><option value="coordinated">Coordinated Fleet+Generator MPC</option></select></label><div class="row"><label>Horizon<input id="mpcH" type="number" value="'+m.horizon+'"></label><label>Sample time<input id="mpcTs" type="number" step=".01" value="'+m.sampleTime+'"></label></div><div class="row"><label>Tolerance<input id="mpcTol" type="number" step=".0001" value="'+m.tolerance+'"></label><label>Max iterations<input id="mpcIter" type="number" value="'+m.maxIterations+'"></label></div><label><input id="mpcWarm" type="checkbox" '+(m.warmStart?'checked':'')+'> warm start</label><label><input id="mpcAdaptive" type="checkbox" '+(m.adaptive?'checked':'')+'> adaptive iterations</label><div id="solverLast" class="status">No MPC run yet.</div>';$('#mpcMode').value=m.mode;for(const id of['mpcMode','mpcH','mpcTs','mpcTol','mpcIter','mpcWarm','mpcAdaptive'])$('#'+id).onchange=()=>{const pp=project.get(),q=pp.controls.mpc;q.mode=$('#mpcMode').value;q.enabled=q.mode!=='off';q.horizon=Number($('#mpcH').value);q.sampleTime=Number($('#mpcTs').value);q.tolerance=Number($('#mpcTol').value);q.maxIterations=Number($('#mpcIter').value);q.warmStart=$('#mpcWarm').checked;q.adaptive=$('#mpcAdaptive').checked;project.set(pp)}
 $('#fleetEditor').innerHTML='<div class="metric"><span>Resources</span><b>'+p.devices.fleet.length+'</b></div><div class="metric"><span>Total Pmax</span><b>'+fmt(p.devices.fleet.reduce((sum,u)=>sum+(u.pmax||0),0),1)+' MW</b></div><div class="metric"><span>Storage energy</span><b>'+fmt(p.devices.fleet.reduce((sum,u)=>sum+(u.energyMWh||0),0),1)+' MWh</b></div>'
}
function renderExperiments(){const p=project.get();$('#mcPanel').innerHTML='<label>Scenarios<input id="mcCount" type="number" min="1" max="1000" value="100"></label><button id="runMC" class="btn wide">Run parallel Monte Carlo</button><div id="mcStatus" class="status">'+JSON.stringify(cpuBackendInfo())+'</div>';$('#performancePanel').innerHTML='<div class="quick-actions">'+[1,10,100,1000].map(n=>'<button class="btn perf" data-n="'+n+'">'+n+' scenarios</button>').join('')+'</div><div id="perfStatus" class="status">Run a benchmark.</div>';$('#sensitivityPanel').innerHTML='<p class="muted">OAT ranking uses cloned experiments so only one parameter changes per comparison.</p><button id="runSensitivity" class="btn">Run default sensitivity</button><div id="sensOut"></div>';$('#sweepPanel').innerHTML='<p class="muted">Multi-dimensional sweeps are generated from the active Project and preserve seed/model hash.</p><button id="runSweep" class="btn">MPC horizon × fleet cap sweep</button><div id="sweepOut"></div>';$('#experimentLibrary').innerHTML=p.experiments.length?'<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Tags</th><th>Action</th></tr></thead><tbody>'+p.experiments.map(e=>'<tr><td>'+esc(e.name)+'</td><td>'+esc((e.tags||[]).join(', '))+'</td><td><button class="btn clone-exp" data-id="'+e.id+'">Clone</button></td></tr>').join('')+'</tbody></table></div>':'<p class="muted">No experiments yet.</p>';bindExperimentActions()}
function renderValidation(){if(!reference){$('#validationBanner').className='banner warn';$('#validationBanner').textContent='Internal validation only — no external reference loaded.';$('#validationMetrics').innerHTML='<p class="muted">Import MATLAB/Simulink, PowerFactory, PSS/E or published numeric CSV/JSON.</p>'}else{const options=['','time','frequency','rocof','voltage','rotorAngle','branchLoading','fleetMW','generatorMW'],map=suggestedMapping(reference),mapping='<details open><summary>Reference channel mapping</summary><div class="table-wrap"><table class="table"><thead><tr><th>Source column</th><th>GridMPC signal</th></tr></thead><tbody>'+reference.headers.map(h=>'<tr><td>'+esc(h)+'</td><td><select class="ref-map" data-header="'+esc(h)+'">'+options.map(o=>'<option value="'+o+'" '+(map[h]===o?'selected':'')+'>'+(o||'ignore')+'</option>').join('')+'</select></td></tr>').join('')+'</tbody></table></div><button id="applyRefMap" class="btn">Apply mapping</button></details>';$('#validationBanner').className='banner '+(validation?.overall==='PASS'?'good':validation?.overall==='FAIL'?'bad':'warn');$('#validationBanner').textContent='External reference: '+reference.source+(validation?' · '+validation.overall:'');$('#validationMetrics').innerHTML=mapping+(validation?'<div class="table-wrap"><table class="table"><thead><tr><th>Signal</th><th>Status</th><th>RMSE</th><th>MAE</th><th>Max</th><th>Corr.</th></tr></thead><tbody>'+Object.entries(validation.signals).map(([k,v])=>'<tr><td>'+k+'</td><td>'+badge(v.status)+'</td><td>'+fmt(v.rmse,5)+'</td><td>'+fmt(v.mae,5)+'</td><td>'+fmt(v.maxError,5)+'</td><td>'+fmt(v.correlation,5)+'</td></tr>').join('')+'</tbody></table></div>':'<p class="muted">Map channels, then run or re-run a study.</p>');setTimeout(()=>{$('#applyRefMap')?.addEventListener('click',()=>{try{const m={};$('.ref-map').forEach(x=>m[x.dataset.header]=x.value);reference=applyReferenceMapping(reference,m);if(lastRun&&reference.data.time){const a=autoAlign(reference,lastRun.rows);aligned=alignReference(reference,lastRun.rows,{offset:a.offset});validation=validateRun(lastRun,aligned,thresholds)}renderValidation()}catch(e){alert(e.message)}})},0)}$('#calibrationPanel').innerHTML='<p class="muted">Differential-Evolution calibration minimizes frequency RMSE against the loaded external reference. Parameter bounds are explicit and every change is reported.</p><div id="calStatus" class="status">Ready.</div>';$('#regressionPanel').innerHTML='<p>Canonical previous baseline: v10 stress benchmark.</p>'+ieeeTable(V10_STRESS_BASELINE)}
function renderPublication(){const p=project.get();$('#figurePanel').innerHTML='<canvas id="pubFreq" class="chart"></canvas><div class="quick-actions"><button id="pngFig" class="btn">PNG ×2</button><button id="svgFig" class="btn">SVG</button></div>';$('#tablePanel').innerHTML=lastRun?ieeeTable(lastRun.metrics):'<p class="muted">Run a study first.</p>';$('#reproPanel').innerHTML='<button id="exportRepro" class="btn wide">Export reproducibility JSON</button><button id="exportValidationCsv" class="btn wide">Validation CSV</button><button id="exportProjectJson" class="btn wide">Project JSON</button>';if(lastRun){requestAnimationFrame(()=>drawSeries($('#pubFreq'),[{name:'Frequency',data:lastRun.rows.map(r=>({x:r.time,y:r.frequency}))}],{title:'Frequency response',yLabel:'Hz'}));$('#pngFig').onclick=()=>exportCanvasPng($('#pubFreq'),'gridmpc-frequency.png',2);$('#svgFig').onclick=()=>downloadText('gridmpc-frequency.svg',seriesSvg([{name:'Frequency',data:lastRun.rows.map(r=>({x:r.time,y:r.frequency}))}],{title:'Frequency response',yLabel:'Hz'}),'image/svg+xml')}bindPublication()}
function renderAdvanced(){const labs=[['AC Power Flow benchmark','acpf'],['Dynamic convergence 20/10/5 ms','conv'],['MPC solver benchmark','solver'],['MPC horizon benchmark','horizon'],['Warm-start A/B','warm'],['Fixed regression suite','regression'],['Microgrid NSGA-II','microgrid'],['N-1 contingency screening','contingency'],['AC WLS state estimation','stateest']];$('#advancedLabs').innerHTML=labs.map(([n,id])=>'<article class="card"><div class="lab-tile"><span><b>'+n+'</b><small class="muted"> publication audit</small></span><button class="btn lab" data-lab="'+id+'">Run</button></div><div id="lab-'+id+'" class="status">Ready.</div></article>').join('')+'<section id="engineeringToolboxHost" style="grid-column:1/-1"></section>';$('.lab').forEach(b=>b.onclick=()=>runLab(b.dataset.lab));renderEngineeringToolbox($('#engineeringToolboxHost'))}
function renderAll(){const p=project.get();$('#projectName').textContent=p.name;$('#projectDirty').style.background=project.dirty?'#ffbd5c':'#44d39e';renderHealth();renderRuns();renderScope();renderModelPalette();renderControls();renderExperiments();renderValidation();renderPublication();renderAdvanced()}

async function runPF(){try{const m=ensureCase(),r=solvePowerFlow(m,{tolerance:1e-10,maxIterations:40,flatStart:true}),v=validateSolvedCase(m,r),s=powerFlowSummary(m,r);$('#networkStatus').innerHTML=(r.converged?badge('PASS'):badge('FAIL'))+' iterations '+r.iterations+' · mismatch '+s.maxMismatch.toExponential(3)+' · min V '+fmt(s.minVoltage,4)+' · worst line '+fmt(s.worstBranchPct,2)+'% · published Vm error '+v.vm.toExponential(2);return r}catch(e){$('#networkStatus').textContent=e.message;throw e}}
async function runDefaultDynamics({name='Generator trip — coordinated MPC',scenario={type:'trip',bus:38,start:1},projectOverride=null}={}){const p=projectOverride||project.get(),m=projectToMatpower(p),r=await simulateDynamics(p,m,{scenario});r.project=p;r.scenario=scenario;if(!projectOverride){lastRun=r;addRun(p,r,{name,tags:['dynamics','v12']});project.set(p);if(r.solver)$('#solverLast').innerHTML='Status '+badge(r.solver.convergedPct>=95?'CONVERGED':'WARN')+' · '+fmt(r.solver.convergedPct,1)+'% converged · max KKT '+fmt(r.solver.maxKKT,6);if(reference){const al=autoAlign(reference,r.rows,{window:2,step:.01});aligned=alignReference(reference,r.rows,{offset:al.offset,method:'linear'});validation=validateRun(r,aligned,thresholds);renderValidation()}renderAll()}return r}

async function runPipeline(){const st=$('#pipelineStatus');try{for(let i=0;i<pipelineSteps.length;i++)pipelineState(i,'ready');pipelineState(0,'running');if(!caseData)await load39(false);pipelineState(0,'done');pipelineState(1,'running');await runPF();pipelineState(1,'done');pipelineState(2,'running');await runDefaultDynamics();pipelineState(2,'done');pipelineState(3,'running');const b=benchmarkRegistry().at(-1),bp=applyBenchmark(project.get(),b);await runDefaultDynamics({name:'stress',scenario:b.scenario,projectOverride:bp});pipelineState(3,'done');pipelineState(4,'running');pipelineState(4,'done');pipelineState(5,'running');const cases=buildMonteCarloCases(project.get(),{samples:10});const pool=new WorkerPool(new URL('./workers/montecarlo.worker.js',import.meta.url),Math.min(2,navigator.hardwareConcurrency||2));await pool.run(project.get(),cases);pipelineState(5,'done');pipelineState(6,'running');if(reference&&lastRun){const a=autoAlign(reference,lastRun.rows);aligned=alignReference(reference,lastRun.rows,{offset:a.offset});validation=validateRun(lastRun,aligned,thresholds)}pipelineState(6,'done');pipelineState(7,'running');renderPublication();pipelineState(7,'done');pipelineState(8,'running');const repro=await reproducibilityRecord(project.get(),{run:lastRun,validation,referenceSource:reference?.source});await buildHtmlReport(project.get(),{run:lastRun,validation,reproducibility:repro});pipelineState(8,'done');st.textContent='Pipeline complete.'}catch(e){st.textContent='Stopped: '+e.message;console.error(e)}}
async function runLab(id){const out=$('#lab-'+id);out.textContent='Running…';try{const p=project.get(),m=ensureCase();if(id==='acpf'){const r=solvePowerFlow(m,{tolerance:1e-10,maxIterations:40,flatStart:true}),v=validateSolvedCase(m,r);out.textContent='Converged='+r.converged+' · iterations='+r.iterations+' · mismatch='+r.maxMismatch.toExponential(3)+' · Vm err='+v.vm.toExponential(3)+' · angle err='+v.va.toExponential(3)}else if(id==='conv'){out.textContent=JSON.stringify(await convergenceStudy(p,m,{type:'trip',bus:38,start:1}),null,2)}else if(id==='solver'){out.textContent=JSON.stringify(benchmarkMPC(p,{dfHz:-.1,genMW:0,fleetMW:0,disturbanceMW:300,soc0:.7}),null,2)}else if(id==='horizon'){out.textContent=JSON.stringify(horizonBenchmark(p,{dfHz:-.1,genMW:0,fleetMW:0,disturbanceMW:300,soc0:.7}),null,2)}else if(id==='warm'){out.textContent=JSON.stringify(warmStartBenchmark(p,Array.from({length:20},(_,i)=>({dfHz:-.02-.004*i,genMW:0,fleetMW:0,disturbanceMW:300,soc0:.7,time:i*.1}))),null,2)}else if(id==='regression'){const rs=[];for(const b of benchmarkRegistry()){const bp=applyBenchmark(p,b),r=await runDefaultDynamics({name:b.name,scenario:b.scenario,projectOverride:bp});rs.push({id:b.id,hash:await benchmarkFingerprint(bp,b),...r.metrics,solver:r.solver})}const pp=project.get();pp.validation??={};pp.validation.regressionHistory??=[];pp.validation.regressionHistory.unshift({time:new Date().toISOString(),appVersion:APP_VERSION,results:rs});project.set(pp);out.textContent=JSON.stringify(rs,null,2)}else if(id==='microgrid'){const r=await optimizeMicrogrid(defaultMicrogrid(),{population:30,generations:20,seed:p.seed});out.textContent='Pareto solutions: '+r.pareto.length+' · method-aligned with Torkan et al. 2022, not exact reproduction.'}else if(id==='contingency'){const r=await contingencyScreen(m,{includeBranches:true,includeGenerators:true,limits:{vmin:.94,vmax:1.06,lineMax:100}});out.textContent=JSON.stringify({total:r.total,worst:r.results.slice(0,12)},null,2)}else if(id==='stateest'){const pf=solvePowerFlow(m,{tolerance:1e-11,maxIterations:40,flatStart:false}),slack=m.bus.findIndex(b=>b[1]===3),meas=[];for(let i=0;i<m.bus.length;i++){meas.push({type:'vm',bus:i,value:pf.Vm[i],sigma:.002});if(i!==slack)meas.push({type:'va',bus:i,value:pf.Va[i]*Math.PI/180,sigma:.001})}const r=acStateEstimation(m,meas,{initial:'flat',tolerance:1e-8,maxIterations:20});out.textContent=JSON.stringify({status:r.status,iterations:r.iterations,objective:r.objective,maxVmError:Math.max(...r.Vm.map((v,i)=>Math.abs(v-pf.Vm[i]))),maxAngleErrorDeg:Math.max(...r.Va.map((v,i)=>Math.abs(v-pf.Va[i])))},null,2)}}catch(e){out.textContent='Error: '+e.message;console.error(e)}}

function bindExperimentActions(){
 $('#designExperiment')?.addEventListener('click',()=>{const d=designExperiment($('#experimentGoal').value,project.get()),p=project.get(),e={id:crypto.randomUUID?.()||Date.now().toString(36),name:'Auto study '+new Date().toLocaleTimeString(),created:new Date().toISOString(),...d,tags:['auto-designed']};p.experiments.push(e);project.set(p);$('#designOutput').textContent=d.scenarios.map(s=>s.name).join(' · ');renderExperiments()});
 $('#runMC')?.addEventListener('click',async()=>{const n=Math.max(1,Math.min(1000,Number($('#mcCount').value))),cases=buildMonteCarloCases(project.get(),{samples:n}),pool=new WorkerPool(new URL('./workers/montecarlo.worker.js',import.meta.url));$('#mcStatus').textContent='Running '+n+' scenarios…';const t=performance.now(),r=await pool.run(project.get(),cases,{onProgress:(d,N)=>$('#mcStatus').textContent='Running '+d+'/'+N});$('#mcStatus').textContent=n+' scenarios in '+fmt(performance.now()-t,0)+' ms · worst nadir '+fmt(Math.min(...r.map(x=>x.nadir)),3)+' Hz'});
 $$('.perf').forEach(b=>b.onclick=async()=>{const n=Number(b.dataset.n),cases=buildMonteCarloCases(project.get(),{samples:n}),pool=new WorkerPool(new URL('./workers/montecarlo.worker.js',import.meta.url));const t=performance.now();$('#perfStatus').textContent='Running '+n+'…';await pool.run(project.get(),cases);$('#perfStatus').textContent=n+' scenarios: '+fmt(performance.now()-t,0)+' ms'});
 $('#runSensitivity')?.addEventListener('click',async()=>{const out=$('#sensOut');out.textContent='Running controlled clones…';const base=project.get(),defs=[
   {parameter:'Inertia scale',delta:.2,make:(p,v)=>p.devices.generators.forEach(g=>g.params.H*=v),lo:.8,hi:1.2},
   {parameter:'Fleet cap',delta:100,make:(p,v)=>p.controls.mpc.fleetCapMW=v,lo:250,hi:450},
   {parameter:'MPC horizon',delta:7.5,make:(p,v)=>p.controls.mpc.horizon=v,lo:5,hi:20},
   {parameter:'Load level',delta:.1,make:(p,v)=>p.devices.loads.forEach(l=>{l.P0*=v;l.Q0*=v}),lo:.9,hi:1.1}
 ],rows=[];for(const d of defs){const lo=structuredClone(base),hi=structuredClone(base);lo.simulation.endTime=hi.simulation.endTime=Math.min(8,base.simulation.endTime);d.make(lo,d.lo);d.make(hi,d.hi);const a=await runDefaultDynamics({projectOverride:lo,scenario:{type:'trip',bus:38,start:1}}),b=await runDefaultDynamics({projectOverride:hi,scenario:{type:'trip',bus:38,start:1}});rows.push({parameter:d.parameter,delta:d.delta,low:a.metrics.nadir,high:b.metrics.nadir})}const ranked=oneAtATimeSensitivity(rows);out.innerHTML='<table class="table"><thead><tr><th>Rank</th><th>Parameter</th><th>Sensitivity</th><th>Low Nadir</th><th>High Nadir</th></tr></thead><tbody>'+ranked.map((r,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(r.parameter)+'</td><td>'+fmt(r.score,6)+'</td><td>'+fmt(r.low,4)+'</td><td>'+fmt(r.high,4)+'</td></tr>').join('')+'</tbody></table>'});
 $('#runSweep')?.addEventListener('click',async()=>{const out=$('#sweepOut'),base=project.get(),horizons=[5,10,20,30],caps=[200,300,400,500],combos=cartesianSweep([{path:'horizon',values:horizons},{path:'cap',values:caps}]),rows=[];out.textContent='Running '+combos.length+' exact clones…';for(const q of combos){const p=structuredClone(base);p.simulation.endTime=Math.min(7,base.simulation.endTime);p.controls.mpc.horizon=q.horizon;p.controls.mpc.fleetCapMW=q.cap;const t=performance.now(),r=await runDefaultDynamics({projectOverride:p,scenario:{type:'trip',bus:38,start:1}});rows.push({...q,nadir:r.metrics.nadir,solverMs:r.solver?.totalSolveMs??performance.now()-t,converged:r.solver?.convergedPct??100})}const pareto=rows.filter(a=>!rows.some(b=>(b.nadir>=a.nadir&&b.solverMs<=a.solverMs)&&(b.nadir>a.nadir||b.solverMs<a.solverMs))),lo=Math.min(...rows.map(x=>x.nadir)),hi=Math.max(...rows.map(x=>x.nadir));out.innerHTML='<div class="table-wrap"><table class="table"><thead><tr><th>Horizon \\ Cap</th>'+caps.map(c=>'<th>'+c+' MW</th>').join('')+'</tr></thead><tbody>'+horizons.map(h=>'<tr><td>N='+h+'</td>'+caps.map(c=>{const r=rows.find(x=>x.horizon===h&&x.cap===c),a=(r.nadir-lo)/(hi-lo||1),star=pareto.includes(r)?' ★':'';return'<td style="background:rgba(98,168,255,'+(.08+.35*a)+')">'+fmt(r.nadir,4)+star+'<br><small>'+fmt(r.solverMs,0)+' ms</small></td>'}).join('')+'</tr>').join('')+'</tbody></table></div><p class="muted">★ non-dominated trade-off: maximize nadir, minimize MPC solve time.</p>'});
 $$('.clone-exp').forEach(b=>b.onclick=()=>{const p=project.get(),e=p.experiments.find(x=>x.id===b.dataset.id);p.experiments.push(cloneExperiment(e));project.set(p);renderExperiments()})
}
function bindPublication(){$('#exportRepro')?.addEventListener('click',async()=>downloadText('gridmpc-reproducibility-v12.json',JSON.stringify(await reproducibilityRecord(project.get(),{run:lastRun,validation,referenceSource:reference?.source}),null,2),'application/json'));$('#exportValidationCsv')?.addEventListener('click',()=>{if(!lastRun||!aligned)return alert('Load external reference and run validation first.');downloadText('gridmpc-validation.csv',validationCsv(lastRun,aligned),'text/csv')});$('#exportProjectJson')?.addEventListener('click',()=>downloadProject(project.get()))}

$('#newProject').onclick=()=>{project.replace(newProject());caseData=null;lastRun=reference=aligned=validation=null;renderAll()};$('#saveProject').onclick=()=>{downloadProject(project.get());project.markClean()};$('#openProject').onchange=async e=>{const p=await loadProjectFile(e.target.files[0]);project.replace(p);caseData=p.network.case||null;renderAll();e.target.value=''};$('#loadIeee39').onclick=()=>load39(false);$('#loadRaminStudy').onclick=async()=>{await load39(false);const p=project.get();p.controls.mpc={...p.controls.mpc,enabled:true,mode:'coordinated',horizon:20,sampleTime:.1,wFrequency:120,wRoCoF:80,wControl:.002,wDeltaU:.03,fleetCapMW:450,genCapMW:900,security:{vmin:.9,lineMax:130}};project.set(p);renderAll();setView('controls')};$('#loadMicrogridStudy').onclick=()=>{setView('advanced');setTimeout(()=>runLab('microgrid'),50)};$('#runPowerFlow').onclick=runPF;$('#runControlAB').onclick=async()=>{const p=project.get(),a=structuredClone(p),b=structuredClone(p);a.controls.mpc.enabled=false;a.controls.mpc.mode='off';const ra=await runDefaultDynamics({name:'A OFF',projectOverride:a}),rb=await runDefaultDynamics({name:'B current',projectOverride:b});alert('A nadir '+fmt(ra.metrics.nadir,4)+' Hz\nB nadir '+fmt(rb.metrics.nadir,4)+' Hz\nΔ '+fmt(rb.metrics.nadir-ra.metrics.nadir,4)+' Hz')};$('#runPipeline').onclick=runPipeline;$('#newExperiment').onclick=()=>setView('experiments');
$('#importCaseBtn').onclick=()=>$('#caseImport').click();$('#caseImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.name.toLowerCase().endsWith('.m')){const m=parseMatpower(await f.text());hydrateNetwork(m);renderAll()}else alert('MATPOWER .m import is implemented now; CSV/JSON network import is handled in Project JSON and will be expanded by schema adapters.')}catch(err){alert(err.message)}e.target.value=''};
$('#referenceImport').onchange=async e=>{try{reference=await importReference(e.target.files[0]);if(lastRun&&reference.data.time){const a=autoAlign(reference,lastRun.rows);aligned=alignReference(reference,lastRun.rows,{offset:a.offset});validation=validateRun(lastRun,aligned,thresholds)}renderValidation()}catch(err){alert(err.message)}e.target.value=''};
$('#runCalibration').onclick=async()=>{if(!reference||!lastRun)return alert('Load an external reference and run a study first.');const p=project.get(),defs=p.devices.generators.slice(0,2).map((g,i)=>({path:'devices.generators.'+i+'.params.H',min:g.params.H*.7,max:g.params.H*1.3}));$('#calStatus').textContent='Calibrating…';const r=await differentialEvolutionCalibration({project:p,reference,parameters:defs,population:8,generations:5,simulate:pp=>runDefaultDynamics({projectOverride:pp}),onProgress:(q,x)=>$('#calStatus').textContent='Generation '+x.generation+' · best RMSE '+fmt(x.best,6)});r.calibrated.calibration??={};r.calibrated.calibration.history??=[];r.calibrated.calibration.history.unshift({time:new Date().toISOString(),method:r.method,seed:r.seed,beforeRmse:r.beforeRmse,afterRmse:r.afterRmse,changes:r.changes,evaluations:r.evaluations,reference:reference.source});project.replace(r.calibrated,{dirty:true});$('#calStatus').textContent='RMSE '+fmt(r.beforeRmse,6)+' → '+fmt(r.afterRmse,6)+' · '+r.changes.map(c=>c.path+': '+fmt(c.before,4)+'→'+fmt(c.after,4)).join(' | ');renderAll()};
$('#buildReport').onclick=async()=>{if(!lastRun)return alert('Run a study first.');const repro=await reproducibilityRecord(project.get(),{run:lastRun,validation,referenceSource:reference?.source}),html=await buildHtmlReport(project.get(),{run:lastRun,validation,reproducibility:repro});downloadText('gridmpc-publication-report-v12.html',html,'text/html')};

project.subscribe(()=>{const p=project.get();$('#projectName').textContent=p.name;$('#projectDirty').style.background=project.dirty?'#ffbd5c':'#44d39e'});
renderPipeline();renderAll();webGpuInfo().then(info=>{const el=$('#perfStatus');if(el)el.textContent='CPU '+JSON.stringify(cpuBackendInfo())+' · WebGPU '+(info.available?'available (not used for core DAE)':'unavailable')});
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
